academica_cenco/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import include

from apps_cenco.login.views import *
from apps_cenco.modulo_grupos.views import *
from apps_cenco.modulo_alumnos.views import *
from django.contrib.auth import views as auth_views

#  {'next_page': '/login'}

urlpatterns = [
    url(r'^$', principal, name="inicio"),  # Valida que sucede cuando se entra al localhost:8000/
    url(r'^accounts/login/$', auth_views.login, {'template_name': 'sesiones/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'sesiones/logout.html'}, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^grupos/', include('apps_cenco.modulo_grupos.urls')),
    url(r'^credenciales/', include('apps_cenco.login.urls')),
    url(r'^alumnos/', include('apps_cenco.modulo_alumnos.urls')),
    url(r'^horarios/', include('apps_cenco.modulo_horarios.urls')),
    url(r'^configuracion/', include('apps_cenco.db_local.urls')),
    url(r'^asistencia/', include('apps_cenco.modulo_asistencia.urls')),
    url(r'^empleados/', include('apps_cenco.modulo_empleados.urls')),
    url(r'^carrera/', include('apps_cenco.modulo_carrera.urls')),
    url(r'^materia/', include('apps_cenco.modulo_materia.urls')),
    url(r'^notas/',  include('apps_cenco.modulo_notas.urls')),
    url(r'^pagos/',  include('apps_cenco.modulo_pagos.urls')),
    url(r'^practicas/',  include('apps_cenco.modulo_practicas.urls')),

    # for reset passwords
    url(r'^password_reset/$', auth_views.password_reset, {'template_name': 'sesiones/password_reset_form.html',
                                                          'html_email_template_name': 'sesiones/password_reset_email.html',
                                                          'subject_template_name': 'sesiones/password_reset_subject.txt'
                                                          }, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, {'template_name': 'sesiones/password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, {'template_name': 'sesiones/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, {'template_name': 'sesiones/password_reset_complete.html'}, name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps_cenco/modulo_asistencia/urls.py
from django.conf.urls import url
import views

#/asistencia/blabla
urlpatterns = [
    url(r'^ver_estados/$', views.ver_reporte_estados, name="director_ver_estados"),
    url(r'^ver_metricas_estado/$', views.ver_metricas_estado, name="director_ver_metricas_estado"),
    url(r'^filtrar_metricas_estados/$', views.filtrar_metricas),
    url(r'^filtrar_estados/$', views.filtrar_estado_por_periodo),
    url(r'^ingresar_asistencia/(?P<id_grupo>\d+)$', views.asistencia_a_clases, name="asistencia_grupo"), #para mostrar pantalla
    url(r'^guardar_asistencia/(?P<id_grupo>\d+)$', views.guardarAsistencia, name="guardar_asistencia_grupo"), #para guardar datos
    url(r'^prof_consultar/(?P<id_grupo>\d+)$', views.prof_detalle_grupo, name="prof_detalle_grupo"),
    url(r'^listado_asistencia/(?P<id_grupo>\d+)$',views.prof_listado_grupo, name="listado_asistencia_pdf"),
    url(r'^detalle_asistencia/(?P<id_alumno>\d+)$',views.detalle_asistencia, name="detalle_asistencia"),
]

apps_cenco/db_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from time import strftime
from django.contrib.auth.models import User
from django.db import models


class Empleado (models.Model):
    codigo = models.AutoField(primary_key=True)
    username = models.OneToOneField(User, blank=True, null=True, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=40)
    apellido = models.CharField(max_length=40)
    direccion = models.TextField()
    correo = models.EmailField(blank=True)
    dui = models.CharField(max_length=10)
    isss = models.CharField(max_length=9)
    afp = models.CharField(max_length=12)
    nit = models.CharField(max_length=17)
    opciones_tipo = (
        ('Asi', 'Asistente'),
        ('Pro', 'Profesor'),
        ('Tec', 'Tecnico')
    )
    tipo = models.CharField(max_length=3, choices=opciones_tipo, default='Pro')

    opciones_estado=(
        ('activo','activo'),
        ('inactivo', 'inactivo')
    )

    estado=models.CharField(max_length=8, choices=opciones_estado, default='activo')

    def __unicode__(self):
        return self.nombre + " " + self.apellido


class Horario (models.Model):
    dias = (
        ('Lunes y Miercoles', 'Lunes y Miercoles'),
        ('Martes y Jueves', 'Martes y Jueves'),
        ('Domingo', 'Domingo'),
        ('Sabado', 'Sabado'),
        ('Viernes', 'Viernes')
    )
    codigo = models.AutoField(primary_key=True)
    dias_asignados = models.CharField(max_length=40, choices=dias)
    hora_inicio = models.TimeField(auto_now=False, auto_now_add=False)
    hora_fin = models.TimeField(auto_now=False, auto_now_add=False)
    cantidad_alumnos = models.IntegerField(default=0, blank=True)

    def __unicode__(self):
        acronimo = ""
        for i in self.dias_asignados.split(" "):
            acronimo += i[0]+" "
        # La I es para especificar un formato de 12 horas, la base tiene los registros en 24 horas.
        acronimo += " de " + self.hora_inicio.strftime("%I:%M") + " a " + self.hora_fin.strftime("%I:%M")
        return acronimo


class Grupo(models.Model):
    codigo = models.AutoField(primary_key=True)
    fechaInicio = models.DateField()
    alumnosInscritos = models.IntegerField(default=0)
    activo_grupo = models.BooleanField(default=True)
    # foreign keys
    horario = models.ForeignKey(Horario, on_delete=models.PROTECT)
    profesor = models.ForeignKey(Empleado, on_delete=models.PROTECT, blank=False)

    def __unicode__(self):
        return self.horario.__unicode__() + " (" + str(self.codigo) + ")"


class Encargado (models.Model):
    codigo = models.AutoField(primary_key=True)
    username = models.OneToOneField(User, blank=True, null=True, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=40)
    apellido = models.CharField(max_length=40)
    direccion = models.TextField()
    correo = models.EmailField(blank=True, null=True)
    dui = models.CharField(max_length=10, blank=True, null=True)

    def __unicode__(self):
        return self.nombre + " " + self.apellido


class Alumno (models.Model):
    codigo = models.AutoField(primary_key=True)
    username = models.OneToOneField(User, blank=True, null=True, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=40)
    apellido = models.CharField(max_length=40)
    direccion = models.TextField()
    correo = models.EmailField(blank=True, null=True)
    fechaNacimiento = models.DateField()
    dui = models.CharField(max_length=10, blank=True, null=True)
    solvente = models.BooleanField(default=False)
    # foreign keys
    encargado = models.ForeignKey(Encargado, on_delete=models.PROTECT, null=True, blank=True)
    # opciones_estado = (
    #     ('activo', 'activo'),
    #     ('inactivo', 'inactivo')
    # )
    #
    # estado = models.CharField(max_length=8, choices=opciones_estado, default='activo')
    def __unicode__(self):
        return self.nombre + " " + self.apellido

    class Meta:
        permissions = (
            ("ver_alumno", "Ver alumno"),
        )


class Telefono (models.Model):
    TIPOS_CHOICES = (('casa', 'Casa',), ('trabajo', 'Trabajo',), ('movil', 'Movil',))
    codigo = models.AutoField(primary_key=True)
    numero = models.CharField(max_length=8, null=False, blank=False)
    alumno = models.ForeignKey(Alumno, on_delete=models.CASCADE, null=True, blank=True)
    encargado = models.ForeignKey(Encargado, on_delete=models.CASCADE, null=True, blank=True)
    empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE, null=True, blank=True)
    tipo = models.CharField(max_length=20, choices=TIPOS_CHOICES)

    def __unicode__(self):
        return self.numero


# Modelos Agregados en Sprint 2

class Inscripcion(models.Model):
    codigo_ins = models.AutoField(primary_key=True)
    fecha_inscripcion = models.DateField()
    actual_inscripcion = models.BooleanField(default=True)
    # foreign keys
    alumno = models.ForeignKey(Alumno, on_delete=models.PROTECT, null=False, blank=False)
    grupo = models.ForeignKey(Grupo, on_delete=models.PROTECT, null=True, blank=True)


class Asistencia(models.Model):
    codigo_asistencia = models.AutoField(primary_key=True)
    fecha_asistencia = models.DateField()
    asistio = models.BooleanField(default=False)
    # foreign keys
    inscripcion = models.ForeignKey(Inscripcion, on_delete=models.CASCADE, null=False, blank=False)


class Estado(models.Model):
    codigo_estado = models.AutoField(primary_key=True)
    tipo_estado = models.CharField(max_length=20, null=False, blank=False)

    def __unicode__(self):
        return self.tipo_estado


class DetalleEstado(models.Model):
    codigo_detalle_e = models.AutoField(primary_key=True)
    fecha_detalle_e = models.DateField()
    actual_detalle_e = models.BooleanField(default=True)
    # foreign keys
    alumno = models.ForeignKey(Alumno, on_delete=models.CASCADE, null=False, blank=False)
    estado = models.ForeignKey(Estado, on_delete=models.CASCADE, null=False, blank=False)

    def __unicode__(self):
        return self.alumno.__unicode__() + " "+ self.estado.__unicode__() + " " + str(self.actual_detalle_e)


class Carrera(models.Model):
    codigo_carrera = models.AutoField(primary_key=True)
    nombre_carrera = models.CharField(max_length=20, null=False, blank=False)
    descripcion_carrera = models.CharField(max_length=200, null=False, blank=False)
    cuota_semanal_carrera = models.DecimalField(max_digits=10, decimal_places=2)
    precio_inscripcion_carrera = models.DecimalField(max_digits=10, decimal_places=2)
    activo_carrera = models.BooleanField(default=True)
    permitir_inscripcion = models.BooleanField(default=True)
    pensum_mes_carrera = models.IntegerField(blank=False, default=10)
    pensum_anio_carrera = models.IntegerField(blank=False, default=2018)


class Materia(models.Model):
    codigo_materia = models.AutoField(primary_key=True)
    nombre_materia = models.CharField(max_length=20, null=False, blank=False)
    descripcion_materia = models.CharField(max_length=200, null=False, blank=False)
    activo_materia = models.BooleanField(default=True)

    def __unicode__(self):
        return self.nombre_materia


class DetallePensum(models.Model):
    codigo_detalle_p = models.AutoField(primary_key=True)
    ordinal_materia_cursa = models.IntegerField(blank=False)
    # foreign keys
    materia = models.ForeignKey(Materia, on_delete=models.PROTECT, null=False, blank=False)
    carrera = models.ForeignKey(Carrera, on_delete=models.PROTECT, null=False, blank=False)


class Documento(models.Model):
    codigo_doc = models.AutoField(primary_key=True)
    nombre_doc = models.CharField(max_length=20, null=False, blank=False)
    descripcion_doc = models.CharField(max_length=200, null=False, blank=False)
    archivo = models.FileField(upload_to='documentos/')
    # foreign keys
    materia = models.ForeignKey(Materia, on_delete=models.PROTECT, null=False, blank=False)


class Expediente(models.Model):
    codigo_expediente = models.AutoField(primary_key=True)
    activo_expediente = models.BooleanField(default=True)
    fecha_inicio_exp = models.DateField()
    fecha_proximo_pago_exp = models.DateField()
    pagado_hasta = models.DateField()
    progreso_expediente = models.DecimalField(max_digits=4, decimal_places=2, default=0.0)
    # foreign keys
    alumno = models.ForeignKey(Alumno, on_delete=models.PROTECT, null=True)
    carrera = models.ForeignKey(Carrera, on_delete=models.PROTECT, null=True)


class Cursa(models.Model):
    codigo_cursa = models.AutoField(primary_key=True)
    nota_final = models.DecimalField(max_digits=6, decimal_places=4, null=True)
    actual_cursa = models.BooleanField(default=True)
    # foreign keys
    materia = models.ForeignKey(Materia, on_delete=models.PROTECT, null=False, blank=False)
    alumno = models.ForeignKey(Alumno, on_delete=models.PROTECT, null=False, blank=False)


class Examen(models.Model):
    codigo_examen = models.AutoField(primary_key=True)
    nombre_examen = models.CharField(max_length=100, null=False, blank=False)
    ponderacion_examen = models.DecimalField(max_digits=5, decimal_places=4)
    fecha_realizacion_examen= models.DateField()
    # foreign keys
    materia = models.ForeignKey(Materia, on_delete=models.PROTECT, null=False, blank=False)


class Evaluacion(models.Model):
    codigo_evaluacion = models.AutoField(primary_key=True)
    # nombre_evaluacion = models.CharField(max_length=100, null=False, blank=False)
    # ponderacion_evaluacion = models.DecimalField(max_digits=5, decimal_places=4)
    nota_evaluacion = models.DecimalField(max_digits=6, decimal_places=4, null=True)
    fecha_ingreso_evaluacion = models.DateField(auto_now=True)
    # fecha_realizacion_evaluacion = models.DateField()
    # foreign keys
    profesor = models.ForeignKey(Empleado, on_delete=models.PROTECT, null=True, blank=True)
    cursa = models.ForeignKey(Cursa, on_delete=models.PROTECT, null=False, blank=False)

apps_cenco/modulo_asistencia/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps_cenco/modulo_asistencia/forms.py
from django import forms


class IntervaloFechaForm(forms.Form):
    fechaInicial = forms.DateField()
    fechaFinal = forms.DateField()

    def __init__(self, *args, **kwargs):
        super(IntervaloFechaForm, self).__init__(*args, **kwargs)
        self.fields['fechaInicial'].label = 'Fecha Inicial'
        self.fields['fechaFinal'].label = 'Fecha Final'


class FechaAsistenciaForm(forms.Form):
    fechaAsistencia = forms.DateField()

    def __init__(self, *args, **kwargs):
        super(FechaAsistenciaForm, self).__init__(*args, **kwargs)
        self.fields['fechaAsistencia'].label = 'Fecha de Asistencia'

templates/modulo_asistencia/director_ver_estados.html
{% extends 'plantillas_base/base_director.html' %}
{% load staticfiles %}

{% block titulo %} Estados {% endblock %}

{% block head_content %}
    <script src="{% static 'js/chartJS/Chart.bundle.js' %}"></script>
    <script src="{% static 'js/chartJS/utils.js' %}"></script>
    <link href=" {% static 'css/alerts_notificaciones.css' %} " rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
	<script src="{% static 'js/jquery-ui.js' %}"></script>

    <style>
        canvas {
            -moz-user-select: none;
            -webkit-user-select: none;
            -ms-user-select: none;
        }
	</style>

{% endblock %}

{% block content %}

    <!-- ALERTAS -->
    <div class="divEscondido" id="mensajeEmergente">
    <span class="btnCerrar">×</span>
        <strong></strong>
    </div>
    <br>
    <h3>Reporte de Estados</h3>
<div style="min-width: 1200px">
    <div style="display: inline-block; border: 2px solid black; float:left; margin-right: 25px; margin-top: 5%; box-shadow: 5px 5px 2px #888888; width: 140px; height: 200px">
        <table class="table-sm table-hover">
            <thead>
                <th>Otros reportes:</th>
            </thead>
            <tbody>
            <tr><td><a href="{% url 'director_ver_estados' %}" style="color: #3836cd">Reporte de Estados
                <img src="{% static 'img/link.png' %}" width="18px" height="18px"/> </a></td></tr>
            <tr><td>Reporte DOS</td></tr>
            <tr><td>Reporte TRES</td></tr>
            <tr><td>Reporte CUATRO</td></tr>
            </tbody>
        </table>

    </div>
<div style="display: inline-block; width: 85%; vert-align: top;" >
    <div>
    <br>
    <table align="center" width="60%">
        <th>
            <span>Tipo de Gr&aacute;fico:</span>
        </th>
        <th>
            <span>Intervalo de Tiempo:</span>
        </th>
        <th>
            <span>Estado de Estudiantes:</span>
        </th>
        <tr>
            <td>
                <select onchange="changePlot(this.value)">
                    <option value="barras" selected>Gr&aacute;fico de Barras</option>
                    <option value="lineas">Gr&aacute;fico de L&iacute;neas</option>
                </select>
            </td>
            <td>
                <select onchange="changeInterval(this.value)" id="id_periodo">
                    <option value="semanal" selected>&uacute;ltima Semana</option>
                    <option value="mensual">&uacute;ltimo Mes</option>
                    <option value="semestral">&uacute;ltimos Seis Meses</option>
                    <option value="anual">&uacute;ltimo A&ntilde;o</option>
                    <option value="personalizado">Personalizado</option>
                </select>
            </td>
            <td>
                <select onchange="changeType(this.value)" id="id_tipo">
                    <option value="activos" selected>Activos</option>
                    <option value="inscritos">Inscritos</option>
                    <option value="retirados">Inactivos</option>
                    <option value="graduados">Graduados</option>
                </select>
            </td>
            <td>
                <div style="display: none" id="espereG">
                    <img src="{% static 'img/ajax-loader.gif' %}">
                    Procesando. Por Favor Espere.
                </div>
            </td>
        </tr>
    </table>
        <br>
        <div id="fechas_filtro" style="display: none; text-align: center; width: 90%"  >
        <form id="enviarFechasForm" action="" method="POST" autocomplete="off">
        {{ form }}
            {% csrf_token %}
            <input type="submit" value="Consultar" id="btnConsultar">
        </form>
        </div>


    </div>
    <div style="width: 100%" id="id_grafico">
		<canvas id="canvas"></canvas>
	</div>
</div>
</div>
    <script>
        $( function() {
            $( "#id_fechaInicial" ).datepicker({
                dateFormat: "dd/mm/yy",
                altFormat: "yy-mm-dd",
                minDate: "-90Y",
                yearRange: "-90:+1",
                monthNames: [ "Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"],
                monthNamesShort: [ "Ene","Feb","Mar","Abr","May","Jun","Jul","Ago","Sep","Oct","Nov","Dic"],
                dayNamesMin: [ "Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sa" ],
                changeMonth: true,
                changeYear: true,
            }); } );

        $( function() {
            $( "#id_fechaFinal" ).datepicker({
                dateFormat: "dd/mm/yy",     //display de la fecha
                altFormat: "yy-mm-dd",      //manejo para backend (NO FUNCIONA), se manda como dateFormat
                minDate: "-90Y",
                yearRange: "-90:+1",
                monthNames: [ "Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"],
                monthNamesShort: [ "Ene","Feb","Mar","Abr","May","Jun","Jul","Ago","Sep","Oct","Nov","Dic"],
                dayNamesMin: [ "Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sa" ],
                changeMonth: true,
                changeYear: true,
            }); } );

    $(document).on('submit', '#enviarFechasForm', function (a) {
        a.preventDefault();
        $('#btnConsultar').attr('disabled', true);
        $('#espereG').css('display', 'inline');
            $.ajax({
                type: 'POST',
                url: '/asistencia/filtrar_estados/',
                data: {
                    opcion: 'personalizado',
                    tipo: opt_tipo,
                    fechaInicial: $('#id_fechaInicial').val(),
                    fechaFinal: $('#id_fechaFinal').val(),
                    csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]').val(),
                },
                success: function (response) {
                  $('#btnConsultar').attr('disabled', false);
                  $('#espereG').css('display', 'none');
                  bar_plot_config.data = response.datos_filtro;
                  line_plot_config.data = response.datos_filtro;
                  chartData.labels = response.fechas_filtro;
                  maximo = response.maximo;
                  tipo = $('#id_tipo').val();
                  bar_plot_config.label = 'Estudiantes ' + tipo;
                  line_plot_config.label = 'Estudiantes ' + tipo;
                  borrarGrafico();
                  cargarGrafico();
                  var m = $('#mensajeEmergente');
                  m.css('display', 'none');
                },
                error: function (response) {
                  $('#btnConsultar').attr('disabled', false);
                  $('#espereG').css('display', 'none');
                  var m = $('#mensajeEmergente');
                  m.children('strong').html(response.responseText);
                  m.css('display','block');
                  m.css('opacity',1);
                  m.removeClass();
                  m.addClass('alerta cuidado');
                  $("html, body").animate({ scrollTop: 0 }, "slow");
                }
            }) });

    function borrarGrafico(){
        $('#canvas').remove();
        $('#id_grafico').append('<canvas id="canvas"></canvas>')
    }

    var maximo = {{ maximo }};
    var opt_tipo = 'activos';
    function changeInterval(valor){
        if (valor !== "personalizado"){
            AJAXcall_simple(valor);
            ocultarFecha();
        }
        else{
            mostrarFecha();
        } }

    function changeType(valor){
        opt_tipo = valor;
        if(valor === 'activos'){
            line_plot_config.borderColor = '#008000';
            bar_plot_config.backgroundColor = '#008000';
        } else if(valor ==='inscritos'){
            line_plot_config.borderColor = '#0000FF';
            bar_plot_config.backgroundColor = '#0000FF';
        }else if(valor === 'retirados'){
            line_plot_config.borderColor = '#FF0000';
            bar_plot_config.backgroundColor = '#FF0000';
        }
        else if (valor === 'graduados'){
            line_plot_config.borderColor = '#808080';
            bar_plot_config.backgroundColor = '#808080';
        }
        var periodo = $('#id_periodo').val();
        if(periodo !== 'personalizado'){
            AJAXcall_simple(periodo);
        } }

    function AJAXcall_simple(option){
        $('#espereG').css('display', 'inline');
        $.ajax({
                type: 'POST',
                url: '/asistencia/filtrar_estados/',
                data: {
                    opcion: option,
                    tipo: opt_tipo,
                    csrfmiddlewaretoken:'{{ csrf_token }}',
                },
                success: function (response) {
                  $('#espereG').css('display', 'none');
                  bar_plot_config.data = response.datos_filtro;
                  line_plot_config.data = response.datos_filtro;
                  chartData.labels = response.fechas_filtro;
                  maximo = response.maximo;
                  tipo = $('#id_tipo').val();
                  bar_plot_config.label = 'Estudiantes ' + tipo;
                  line_plot_config.label = 'Estudiantes ' + tipo;
                  borrarGrafico();
                  cargarGrafico();
                  var m = $('#mensajeEmergente');
                  m.css('display', 'none');
                },
                error: function (response) {
                    $('#espereG').css('display', 'none');
                }
            }) }

    function mostrarFecha(){
        $('#fechas_filtro').removeClass();
        $('#fechas_filtro').css('display', 'block');
    }

    function ocultarFecha(){
        $('#fechas_filtro').removeClass();
        $('#fechas_filtro').css('display', 'none');
    }

    function changePlot(selected){
        if (selected === "lineas"){
            chartData.datasets = [ line_plot_config ];
        }
        if (selected === "barras"){
            chartData.datasets = [ bar_plot_config ];
        }
        cargarGrafico();
    }

    var plot_data = [{% for detalle in detalle_semanal %}{{ detalle.count }}, {% endfor %} ];

    var line_plot_config = {
				type: 'line',
				label: 'Estudiantes activos',
				borderColor: '#008000',
				borderWidth: 2,
				fill: false,
				data: plot_data,};

    var bar_plot_config = {
				type: 'bar',
				label: 'Estudiantes activos',
				backgroundColor: '#008000',
				data: plot_data,
				borderColor: 'white',
				borderWidth: 2};

    var chartData = {
			labels: [{% for detalle in detalle_semanal %}'{{ detalle.fecha_detalle_e | date:"d M"}}',{% endfor %}],
			datasets: [ bar_plot_config ]};

    function cargarGrafico(){
        var ctx = document.getElementById('canvas').getContext('2d');
			window.myMixedChart = new Chart(ctx, {
				type: 'bar',
				data: chartData,
				options: {
					responsive: true,
					title: {
						display: true,
						text: 'Reporte de Estados'
					},
					tooltips: {
						mode: 'index',
						intersect: true
					},
					scales: {
					    yAxes: [{
					        scaleLabel: {
					          display: true,
                              labelString: 'Cantidad de Estudiantes',
                            },
					        ticks: {
					            beginAtZero: true,
                                callback: function(value) {if (value % 1 === 0) {return value;}},
                                max: maximo,

					        }
					    }],
                        xAxes: [{
                            scaleLabel: {
					          display: true,
                              labelString: 'Fecha de actividad',
                            },
                        }]
					}
				}
			});
    }

		window.onload = function() {
            var fecha1 = document.getElementById('id_fechaInicial');
            fecha1.onkeydown = function (e) { e.preventDefault(); };
            var fecha2 = document.getElementById('id_fechaFinal');
            fecha2.onkeydown = function (e) { e.preventDefault(); };
            cargarGrafico();
		};
	</script>

    <script src="{% static 'js/cerrar_alertas.js' %}"></script>
{% endblock %}

templates/modulo_asistencia/encargado_consultar_asistencia.html
{% extends 'plantillas_base/base_encargado.html' %}
{% load staticfiles %}

{% block titulo %} Registro de Asistencia {% endblock %}

{% block content %}

    <table class="table table-sm" style="width: 30%">
    <thead><th>Fecha De Clases</th><th>Asistencia</th></thead>
    {% for a in asistencias %}
        <tr><td>{{ a.fecha_asistencia }}</td><td>{% if a.asistio %}
            <img src="{% static 'img/asist_check.jpeg'%}" style="width: 24px; height: 24px;" >{% else %}
        <img src="{% static 'img/asistencia_bad.jpeg'%}" style="width: 24px; height: 24px;" >{% endif %}</td></tr>
    {% endfor %}
    </table>



{% endblock %}