academica_cenco/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import include

from apps_cenco.login.views import *
from apps_cenco.modulo_grupos.views import *
from apps_cenco.modulo_alumnos.views import *
from django.contrib.auth import views as auth_views

#  {'next_page': '/login'}

urlpatterns = [
    url(r'^$', principal, name="inicio"),  # Valida que sucede cuando se entra al localhost:8000/
    url(r'^accounts/login/$', auth_views.login, {'template_name': 'sesiones/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'sesiones/logout.html'}, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^grupos/', include('apps_cenco.modulo_grupos.urls')),
    url(r'^credenciales/', include('apps_cenco.login.urls')),
    url(r'^alumnos/', include('apps_cenco.modulo_alumnos.urls')),
    url(r'^horarios/', include('apps_cenco.modulo_horarios.urls')),
    url(r'^configuracion/', include('apps_cenco.db_local.urls')),
    url(r'^asistencia/', include('apps_cenco.modulo_asistencia.urls')),
    url(r'^empleados/', include('apps_cenco.modulo_empleados.urls')),
    url(r'^carrera/', include('apps_cenco.modulo_carrera.urls')),
    url(r'^materia/', include('apps_cenco.modulo_materia.urls')),
    url(r'^notas/',  include('apps_cenco.modulo_notas.urls')),
    url(r'^pagos/',  include('apps_cenco.modulo_pagos.urls')),
    url(r'^practicas/',  include('apps_cenco.modulo_practicas.urls')),

    # for reset passwords
    url(r'^password_reset/$', auth_views.password_reset, {'template_name': 'sesiones/password_reset_form.html',
                                                          'html_email_template_name': 'sesiones/password_reset_email.html',
                                                          'subject_template_name': 'sesiones/password_reset_subject.txt'
                                                          }, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, {'template_name': 'sesiones/password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, {'template_name': 'sesiones/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, {'template_name': 'sesiones/password_reset_complete.html'}, name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps_cenco/modulo_notas/urls.py
from django.conf.urls import url

from apps_cenco.modulo_notas import views

urlpatterns = [
    url(r'^ingresar_notas/(?P<id_grupo>\d+)$', views.ingresar_nota),
    url(r'^consultar_evaluaciones/$', views.consultar_evaluaciones),
    url(r'^finalizar_materia/(?P<id_alumno>\d+)$', views.finalizar_materia),
    url(r'^record_notas/$', views.ver_record_notas),
    url(r'^ingresar_evaluaciones/$', views.ingresar_evaluaciones),

]

apps_cenco/db_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from time import strftime
from django.contrib.auth.models import User
from django.db import models


class Empleado (models.Model):
    codigo = models.AutoField(primary_key=True)
    username = models.OneToOneField(User, blank=True, null=True, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=40)
    apellido = models.CharField(max_length=40)
    direccion = models.TextField()
    correo = models.EmailField(blank=True)
    dui = models.CharField(max_length=10)
    isss = models.CharField(max_length=9)
    afp = models.CharField(max_length=12)
    nit = models.CharField(max_length=17)
    opciones_tipo = (
        ('Asi', 'Asistente'),
        ('Pro', 'Profesor'),
        ('Tec', 'Tecnico')
    )
    tipo = models.CharField(max_length=3, choices=opciones_tipo, default='Pro')

    opciones_estado=(
        ('activo','activo'),
        ('inactivo', 'inactivo')
    )

    estado=models.CharField(max_length=8, choices=opciones_estado, default='activo')

    def __unicode__(self):
        return self.nombre + " " + self.apellido


class Horario (models.Model):
    dias = (
        ('Lunes y Miercoles', 'Lunes y Miercoles'),
        ('Martes y Jueves', 'Martes y Jueves'),
        ('Domingo', 'Domingo'),
        ('Sabado', 'Sabado'),
        ('Viernes', 'Viernes')
    )
    codigo = models.AutoField(primary_key=True)
    dias_asignados = models.CharField(max_length=40, choices=dias)
    hora_inicio = models.TimeField(auto_now=False, auto_now_add=False)
    hora_fin = models.TimeField(auto_now=False, auto_now_add=False)
    cantidad_alumnos = models.IntegerField(default=0, blank=True)

    def __unicode__(self):
        acronimo = ""
        for i in self.dias_asignados.split(" "):
            acronimo += i[0]+" "
        # La I es para especificar un formato de 12 horas, la base tiene los registros en 24 horas.
        acronimo += " de " + self.hora_inicio.strftime("%I:%M") + " a " + self.hora_fin.strftime("%I:%M")
        return acronimo


class Grupo(models.Model):
    codigo = models.AutoField(primary_key=True)
    fechaInicio = models.DateField()
    alumnosInscritos = models.IntegerField(default=0)
    activo_grupo = models.BooleanField(default=True)
    # foreign keys
    horario = models.ForeignKey(Horario, on_delete=models.PROTECT)
    profesor = models.ForeignKey(Empleado, on_delete=models.PROTECT, blank=False)

    def __unicode__(self):
        return self.horario.__unicode__() + " (" + str(self.codigo) + ")"


class Encargado (models.Model):
    codigo = models.AutoField(primary_key=True)
    username = models.OneToOneField(User, blank=True, null=True, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=40)
    apellido = models.CharField(max_length=40)
    direccion = models.TextField()
    correo = models.EmailField(blank=True, null=True)
    dui = models.CharField(max_length=10, blank=True, null=True)

    def __unicode__(self):
        return self.nombre + " " + self.apellido


class Alumno (models.Model):
    codigo = models.AutoField(primary_key=True)
    username = models.OneToOneField(User, blank=True, null=True, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=40)
    apellido = models.CharField(max_length=40)
    direccion = models.TextField()
    correo = models.EmailField(blank=True, null=True)
    fechaNacimiento = models.DateField()
    dui = models.CharField(max_length=10, blank=True, null=True)
    solvente = models.BooleanField(default=False)
    # foreign keys
    encargado = models.ForeignKey(Encargado, on_delete=models.PROTECT, null=True, blank=True)
    # opciones_estado = (
    #     ('activo', 'activo'),
    #     ('inactivo', 'inactivo')
    # )
    #
    # estado = models.CharField(max_length=8, choices=opciones_estado, default='activo')
    def __unicode__(self):
        return self.nombre + " " + self.apellido

    class Meta:
        permissions = (
            ("ver_alumno", "Ver alumno"),
        )


class Telefono (models.Model):
    TIPOS_CHOICES = (('casa', 'Casa',), ('trabajo', 'Trabajo',), ('movil', 'Movil',))
    codigo = models.AutoField(primary_key=True)
    numero = models.CharField(max_length=8, null=False, blank=False)
    alumno = models.ForeignKey(Alumno, on_delete=models.CASCADE, null=True, blank=True)
    encargado = models.ForeignKey(Encargado, on_delete=models.CASCADE, null=True, blank=True)
    empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE, null=True, blank=True)
    tipo = models.CharField(max_length=20, choices=TIPOS_CHOICES)

    def __unicode__(self):
        return self.numero


# Modelos Agregados en Sprint 2

class Inscripcion(models.Model):
    codigo_ins = models.AutoField(primary_key=True)
    fecha_inscripcion = models.DateField()
    actual_inscripcion = models.BooleanField(default=True)
    # foreign keys
    alumno = models.ForeignKey(Alumno, on_delete=models.PROTECT, null=False, blank=False)
    grupo = models.ForeignKey(Grupo, on_delete=models.PROTECT, null=True, blank=True)


class Asistencia(models.Model):
    codigo_asistencia = models.AutoField(primary_key=True)
    fecha_asistencia = models.DateField()
    asistio = models.BooleanField(default=False)
    # foreign keys
    inscripcion = models.ForeignKey(Inscripcion, on_delete=models.CASCADE, null=False, blank=False)


class Estado(models.Model):
    codigo_estado = models.AutoField(primary_key=True)
    tipo_estado = models.CharField(max_length=20, null=False, blank=False)

    def __unicode__(self):
        return self.tipo_estado


class DetalleEstado(models.Model):
    codigo_detalle_e = models.AutoField(primary_key=True)
    fecha_detalle_e = models.DateField()
    actual_detalle_e = models.BooleanField(default=True)
    # foreign keys
    alumno = models.ForeignKey(Alumno, on_delete=models.CASCADE, null=False, blank=False)
    estado = models.ForeignKey(Estado, on_delete=models.CASCADE, null=False, blank=False)

    def __unicode__(self):
        return self.alumno.__unicode__() + " "+ self.estado.__unicode__() + " " + str(self.actual_detalle_e)


class Carrera(models.Model):
    codigo_carrera = models.AutoField(primary_key=True)
    nombre_carrera = models.CharField(max_length=20, null=False, blank=False)
    descripcion_carrera = models.CharField(max_length=200, null=False, blank=False)
    cuota_semanal_carrera = models.DecimalField(max_digits=10, decimal_places=2)
    precio_inscripcion_carrera = models.DecimalField(max_digits=10, decimal_places=2)
    activo_carrera = models.BooleanField(default=True)
    permitir_inscripcion = models.BooleanField(default=True)
    pensum_mes_carrera = models.IntegerField(blank=False, default=10)
    pensum_anio_carrera = models.IntegerField(blank=False, default=2018)


class Materia(models.Model):
    codigo_materia = models.AutoField(primary_key=True)
    nombre_materia = models.CharField(max_length=20, null=False, blank=False)
    descripcion_materia = models.CharField(max_length=200, null=False, blank=False)
    activo_materia = models.BooleanField(default=True)

    def __unicode__(self):
        return self.nombre_materia


class DetallePensum(models.Model):
    codigo_detalle_p = models.AutoField(primary_key=True)
    ordinal_materia_cursa = models.IntegerField(blank=False)
    # foreign keys
    materia = models.ForeignKey(Materia, on_delete=models.PROTECT, null=False, blank=False)
    carrera = models.ForeignKey(Carrera, on_delete=models.PROTECT, null=False, blank=False)


class Documento(models.Model):
    codigo_doc = models.AutoField(primary_key=True)
    nombre_doc = models.CharField(max_length=20, null=False, blank=False)
    descripcion_doc = models.CharField(max_length=200, null=False, blank=False)
    archivo = models.FileField(upload_to='documentos/')
    # foreign keys
    materia = models.ForeignKey(Materia, on_delete=models.PROTECT, null=False, blank=False)


class Expediente(models.Model):
    codigo_expediente = models.AutoField(primary_key=True)
    activo_expediente = models.BooleanField(default=True)
    fecha_inicio_exp = models.DateField()
    fecha_proximo_pago_exp = models.DateField()
    pagado_hasta = models.DateField()
    progreso_expediente = models.DecimalField(max_digits=4, decimal_places=2, default=0.0)
    # foreign keys
    alumno = models.ForeignKey(Alumno, on_delete=models.PROTECT, null=True)
    carrera = models.ForeignKey(Carrera, on_delete=models.PROTECT, null=True)


class Cursa(models.Model):
    codigo_cursa = models.AutoField(primary_key=True)
    nota_final = models.DecimalField(max_digits=6, decimal_places=4, null=True)
    actual_cursa = models.BooleanField(default=True)
    # foreign keys
    materia = models.ForeignKey(Materia, on_delete=models.PROTECT, null=False, blank=False)
    alumno = models.ForeignKey(Alumno, on_delete=models.PROTECT, null=False, blank=False)


class Examen(models.Model):
    codigo_examen = models.AutoField(primary_key=True)
    nombre_examen = models.CharField(max_length=100, null=False, blank=False)
    ponderacion_examen = models.DecimalField(max_digits=5, decimal_places=4)
    fecha_realizacion_examen= models.DateField()
    # foreign keys
    materia = models.ForeignKey(Materia, on_delete=models.PROTECT, null=False, blank=False)


class Evaluacion(models.Model):
    codigo_evaluacion = models.AutoField(primary_key=True)
    # nombre_evaluacion = models.CharField(max_length=100, null=False, blank=False)
    # ponderacion_evaluacion = models.DecimalField(max_digits=5, decimal_places=4)
    nota_evaluacion = models.DecimalField(max_digits=6, decimal_places=4, null=True)
    fecha_ingreso_evaluacion = models.DateField(auto_now=True)
    # fecha_realizacion_evaluacion = models.DateField()
    # foreign keys
    profesor = models.ForeignKey(Empleado, on_delete=models.PROTECT, null=True, blank=True)
    cursa = models.ForeignKey(Cursa, on_delete=models.PROTECT, null=False, blank=False)

apps_cenco/modulo_notas/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps_cenco/modulo_notas/forms.py
# -*- coding: utf-8 -*-
from django import forms

from apps_cenco.db_app.models import Evaluacion, Examen


class CrearEditarExamenForm(forms.ModelForm):
    class Meta:
        model = Examen
        fields = [
            'nombre_examen',
            'ponderacion_examen',
            'fecha_realizacion_examen',
            'materia',
        ]

        labels = {
            'nombre_examen': 'Nombre de la Evaluación',
            'ponderacion_examen': 'Ponderación',
            'fecha_realizacion_examen': 'Fecha en que se realizará',
            'materia': 'Asignatura',
        }

        widgets = {
            'nombre_examen': forms.TextInput(attrs={'class': 'form-control', 'required': True}),
            'ponderacion_examen': forms.NumberInput(attrs={'class': 'form-control', 'required': True}),
            'fecha_realizacion_examen': forms.DateInput(attrs={'class': 'form-control', 'required': True}),
            'materia': forms.Select(attrs={'class': 'form-control', 'required': True}),
        }

templates/modulo_notas/consultar_evaluaciones.html
{% extends 'plantillas_base/base_director.html' %}
{% load staticfiles %}
{% block titulo %}Evaluaciones{% endblock %}

{% block head_content %}
<link href=" {% static 'css/contenido_colapsable.css' %} " rel="stylesheet">
{% endblock %}

{% block content %}
    <br>
    <h3>Consultar Evaluaciones</h3>
    <br>
    {% for m in materias %}
    <p></p>
        <button class="collapsible" style="width: 80%;"><strong><div style="display: inline-block;" class="accion">[Expandir &#9660;]</div> &nbsp; &nbsp;&nbsp; {{ m.nombre_materia }}</strong></button>
        <div class="content" style="width: 80%">
    <table class="table border-dark">
        <thead>
        <th style="width: 100px">Codigo</th>
        <th style="width: 150px">Nombre</th>
        <th>Ponderaci&oacute;n</th>
        <th>Fecha de Realizaci&oacute;n</th>
        </thead>
    <tbody>
    {% for e in examenes %}
        {% if e.materia == m %}
           <tr><td>{{ e.codigo_examen }}</td>
               <td>{{ e.nombre_examen }}</td>
               <td>{{ e.ponderacion_examen }}</td>
               <td>{{ e.fecha_realizacion_examen }}</td></tr>
        {% endif %}
    {% endfor %}
    </tbody>
    </table>
    </div>
    {% endfor %}

<script src="{% static 'js/contenido_colapsable.js' %}"></script>
{% endblock %}

templates/modulo_notas/consultar_record_notas.html
{% extends 'plantillas_base/base_alumno.html' %}
{% load staticfiles %}

{% block titulo %}Record de Notas{% endblock %}

{% block head_content %}
    <link href=" {% static 'css/contenido_colapsable.css' %} " rel="stylesheet">
    <link href=" {% static 'css/alerts_notificaciones.css' %} " rel="stylesheet">
{% endblock %}

{% block content %}

    <br>
    <h3>Sus Calificaciones</h3>
    <br>
    {% for c in cursa %}
    <p></p>
        <button class="collapsible" style="width: 80%;">
            <strong><div style="display: inline-block;" class="accion">[Expandir &#9660;]</div>
                &nbsp; &nbsp;&nbsp; {{ c.materia.nombre_materia }} &nbsp; {% if c.actual_cursa %} [EN CURSO] {% endif %}
            </strong></button>
        <div class="content" style="width: 80%">
    <table class="table border-dark">
        <thead>
        {% for e in evaluaciones %}
            {% if e.cursa == c %}
        <th>{{ e.examen.nombre_examen }}</th>
            {% endif %}
        {% endfor %}
        <th>Nota Promedio</th>
        </thead>
    <tbody>
    <tr>
    {% for e in evaluaciones %}
         {% if e.cursa == c %}
           <td>{{ e.nota_evaluacion }}</td>
        {% endif %}
    {% endfor %}
    <td>{{ c.nota_final }}</td></tr>
    </tbody>
    </table>
    </div>
     {% endfor %}
    <script src="{% static 'js/contenido_colapsable.js' %}"></script>
{% endblock %}

templates/modulo_notas/finalizar_materia.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/modulo_notas/ingresar_evaluaciones.html
{% extends 'plantillas_base/base_director.html' %}
{% load staticfiles %}

{% block titulo %}Gesti&oacute;n de Calificaciones{% endblock %}

{% block head_content %}
    <link href=" {% static 'css/alerts_notificaciones.css' %} " rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/jquery-1.12.1ui/jquery-ui.css' %}">
    <script src="{% static 'js/jquery-1.12.4/jquery-ui.js' %}"></script>

    <script>
    $( function() {
        $( "#id_fecha_realizacion_examen" ).datepicker({
            dateFormat: "dd/mm/yy",
            altFormat: "yy-mm-dd",
            minDate: "-90Y",
            yearRange: "-90:+1",
            monthNames: [ "Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"],
            monthNamesShort: [ "Ene","Feb","Mar","Abr","May","Jun","Jul","Ago","Sep","Oct","Nov","Dic"],
            dayNamesMin: [ "Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sa" ],
            changeMonth: true,
            changeYear: true,
        });
    } );

</script>

{% endblock %}

{% block content %}
    {% if post %}
        <!-- ALERTAS -->
        <div class="alerta {% if error %}accionPeligrosa{% elif alert %}cuidado{% else %}exito{% endif %}" id="mensajeEmergente">
        <span class="btnCerrar">&times;</span>
            <strong>{{ mensaje }}</strong>
        </div>
    {% endif %}
    <br>
    <h3>Ingresar Nueva Evaluaci&oacute;n</h3>

<div style="width: 50%;">
    <form method="POST">
    {% csrf_token %}
    <tr><th><label for="id_nombre_examen">Nombre de la Evaluación:</label></th><td><input type="text" name="nombre_examen" id="id_nombre_examen" required class="form-control" maxlength="100" /></td></tr>
<tr><th><label for="id_ponderacion_examen">Ponderación:</label></th><td><input type="number" name="ponderacion_examen" step="0.0001" required class="form-control" id="id_ponderacion_examen" /></td></tr>
<tr><th><label for="id_fecha_realizacion_examen">Fecha en que se realizará:</label></th><td><input type="text" name="fecha_realizacion_examen" required class="form-control" id="id_fecha_realizacion_examen" /></td></tr>
<tr><th><label for="id_materia">Asignatura:</label></th><td>
    <select name="materia" required class="form-control" id="id_materia">
  <option value="" selected>---------</option>
    {% for m in materias %}
        <option value="{{ m.pk }}">{{ m.nombre_materia }} ({{ m.porcentaje }}% ya asignado)</option>
    {% endfor %}

</select></td></tr>
    <tr><p></p></tr>
    <input type="submit" class="btn-primary btn" value="Guardar Evaluaci&oacute;n">
    </form>
</div>



    <div style="display: none" id="espereG">
        <img src="{% static 'img/ajax-loader.gif' %}">
        Procesando. Por Favor Espere.
    </div>

<script src="{% static 'js/cerrar_alertas.js' %}"></script>
{% endblock %}

templates/modulo_notas/ingresar_modificar_notas.html
{% extends 'plantillas_base/base_alumno.html' %}
{% load staticfiles %}

{% block titulo %}Gesti&oacute;n de Calificaciones{% endblock %}

{% block head_content %}
    <link href=" {% static 'css/alerts_notificaciones.css' %} " rel="stylesheet">

    <script>

window.onload = function(){
          filterSelection('{{ mats.0.pk }}')
      };

function clearHeaderFields(){

    $('#id_nombre_evaluacion').val("") ;
    $('#id_ponderacion_evaluacion').val("");
    $('#id_fecha_realizacion_evaluacion').val("");
}

function filterSelection(c) {
    clearHeaderFields();
  var x, i;
  x = document.getElementsByClassName("divGrupo");
  if(c==null) c = "all";
  for (i = 0; i < x.length; i++) {
    RemoveClass(x[i], "show");
    if (x[i].className.indexOf(c) > -1) {
        AddClass(x[i], "show");

    }
  }
}

function AddClass(element, name) {
  var i, arr1, arr2;
  arr1 = element.className.split(" ");
  arr2 = name.split(" ");
  for (i = 0; i < arr2.length; i++) {
    if (arr1.indexOf(arr2[i]) == -1) {element.className += " " + arr2[i];}
  }
}

function RemoveClass(element, name) {
  var i, arr1, arr2;
  arr1 = element.className.split(" ");
  arr2 = name.split(" ");
  for (i = 0; i < arr2.length; i++) {
    while (arr1.indexOf(arr2[i]) > -1) {
      arr1.splice(arr1.indexOf(arr2[i]), 1);
    }
  }
  element.className = arr1.join(" ");
}


$(document).on('submit', '#notasForm', function (a) {
    a.preventDefault();
    if (form_esValido() && select_esValido()) {
        $('#errorDeBtn').html("");
        var list = {};
        var elementos = document.getElementsByClassName("show")[0].getElementsByTagName("tr");
        for (var i = 1; i < elementos.length; i++) {
            var celda = elementos[i].getElementsByTagName("td")[5].firstChild;
            list[celda.id] = celda.value;
        }
        var select = document.getElementById("selectMateria");
        var materia_id = select.options[select.selectedIndex].value;

        var select2 = document.getElementsByClassName("show")[0].getElementsByTagName("select")[0];
        var examen_id = select2.options[select2.selectedIndex].value;

        $('#btnGuardarNotas').attr('disabled', true);
        $('#espereG').css('display', 'block');
        $.ajax({
            type: 'POST',
            url: '/notas/ingresar_notas/{{ grupo.pk }}',
            datatype: 'json',
            data: {
                JSONdata: JSON.stringify(list),
                materia: materia_id,
                examen: examen_id,
                csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]').val(),
            },
            success: function (response) {
                $('#btnGuardarNotas').attr('disabled', false);
                $('#espereG').css('display', 'none');
                var m = $('#mensajeEmergente');
                m.children('strong').html(response);
                m.css('display', 'block');
                m.css('opacity', 1);
                m.removeClass();
                m.addClass('alerta exito');
                $("html, body").animate({scrollTop: 0}, "slow");
            },
            error: function (response) {

                $('#btnGuardarNotas').attr('disabled', false);
                $('#espereG').css('display', 'none');
                var m = $('#mensajeEmergente');
                m.children('strong').html(response.responseText);
                m.css('display', 'block');
                m.css('opacity', 1);
                m.removeClass();
                m.addClass('alerta cuidado');
                $("html, body").animate({scrollTop: 0}, "slow");
            }
        })
    }else{
        if (form_esValido())
        $('#errorDeBtn').html("<font color=\"red\"> *Debe seleccionar una evaluaci&oacute;n correctamente</font>");
        else
        $('#errorDeBtn').html("<font color=\"red\"> *Las calificaciones deben tener un valor entre 0.0 y 10.0 puntos.</font>");
    }
    });


    function form_esValido() {
        var inputs = document.getElementsByClassName("show")[0].getElementsByClassName("calif");
        for (var i=0; i<=inputs.length-1; i++){
            var x = inputs[i].valueAsNumber;
            if (x < 0.0 || x > 10.0 || isNaN(x)){return false;}
        }
        return true;
    }

    function select_esValido() {
        var select = document.getElementsByClassName("show")[0].getElementsByTagName("form")[0].getElementsByTagName("select");
        return select[0].options.length !== 0;
    }


    </script>

    <style>
    body {
 font-size:16px;
}

.divGrupo {
	width: 28%;
    padding-left:3%;
    margin: 1%;
    text-align:left;
    display: none;

}

.divNotifGrupo {
    width: 90%;
    border: 2px solid black;
    padding:2%;
    margin: 1%;
    display: inline-block;
    text-align:left;
    box-shadow: 5px 5px 2px #888888;

}

.show {
  display: inline-grid;
}

    </style>


{% endblock %}

{% block content %}
    <br>
        <!-- ALERTAS -->
        <div class="divEscondido" id="mensajeEmergente">
        <span class="btnCerrar">&times;</span>
            <strong></strong>
        </div>

    <h3>{% if editar %}Editar {% else %}Ingresar {% endif %}Calificaciones. Grupo {{ grupo.pk }} </h3>
    <h4>Horario: {{ grupo.horario.dias_asignados }} de {{ grupo.horario.hora_inicio|time:"h:i A" }} a {{ grupo.horario.hora_fin|time:"h:i A" }}</h4>
    <br>
    <div style="width: 70%; padding-left: 4%;">

    <select  class="custom-select" onchange="filterSelection(this[this.selectedIndex].id)" id="selectMateria" style="width: 50.8%">
    {% for m in mats %}<option id="{{ m.pk }}" value="{{ m.pk }}" {% if forloop.first %}selected{% endif %}>{{ m }}</option>{% endfor %}
    </select>
    </div>
    <div style="display: block; padding-left: 10px;" id="errorDeBtn" ></div>
        {% for m in mats %}
       <div style="width: 70%" class="all divGrupo {{ m.pk }}">

       <br>
       <form method="POST" id="notasForm">
       {% csrf_token %}
           <select id="selectExamen" class="custom-select" style="width: 50%">
        {% for e in examenes %}
            {% if e.materia == m %}<option id="{{ e.pk }}" value="{{ e.pk }}">{{ e.nombre_examen }}</option>{% endif %}
            {% endfor %}
       </select>
            <div style="min-height: 60px"></div>
            <table id="tabla" class="table-sm table">
                <thead><th>Codigo</th><th>Nombre</th><th>Apellido</th><th>Cod. Materia</th><th>Materia</th><th>Calificaci&oacute;n</th></thead><tbody>
            {% for a in inscripciones %}{% if m.pk == a.materia_id %}
                <tr><td>{{ a.codigo }}</td>
                    <td>{{ a.nombre }}</td>
                    <td>{{ a.apellido }}</td>
                    <td>{{ a.materia_id }}</td>
                    <td>{{ a.nombre_materia }}</td>
                    <td><input class="calif" type="number" id="{{ a.alumno.pk }}" step="0.01" placeholder="0.00" min="0.00" max="10.00" required></td></tr>
                {% endif %}
            {% endfor %}
            </tbody>
                </table>
                       <input type="submit" id="btnGuardarNotas" class="btn btn-primary" value="Guardar calificaciones">
        </form>
             </div>

        {% endfor %}
    <div style="display: none" id="espereG">
        <img src="{% static 'img/ajax-loader.gif' %}">
        Procesando. Por Favor Espere.
    </div>

<script src="{% static 'js/cerrar_alertas.js' %}"></script>
{% endblock %}