academica_cenco/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import include

from apps_cenco.login.views import *
from apps_cenco.modulo_grupos.views import *
from apps_cenco.modulo_alumnos.views import *
from django.contrib.auth import views as auth_views

#  {'next_page': '/login'}

urlpatterns = [
    url(r'^$', principal, name="inicio"),  # Valida que sucede cuando se entra al localhost:8000/
    url(r'^accounts/login/$', auth_views.login, {'template_name': 'sesiones/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'sesiones/logout.html'}, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^grupos/', include('apps_cenco.modulo_grupos.urls')),
    url(r'^credenciales/', include('apps_cenco.login.urls')),
    url(r'^alumnos/', include('apps_cenco.modulo_alumnos.urls')),
    url(r'^horarios/', include('apps_cenco.modulo_horarios.urls')),
    url(r'^configuracion/', include('apps_cenco.db_local.urls')),
    url(r'^asistencia/', include('apps_cenco.modulo_asistencia.urls')),
    url(r'^empleados/', include('apps_cenco.modulo_empleados.urls')),
    url(r'^carrera/', include('apps_cenco.modulo_carrera.urls')),
    url(r'^materia/', include('apps_cenco.modulo_materia.urls')),
    url(r'^notas/',  include('apps_cenco.modulo_notas.urls')),
    url(r'^pagos/',  include('apps_cenco.modulo_pagos.urls')),
    url(r'^practicas/',  include('apps_cenco.modulo_practicas.urls')),

    # for reset passwords
    url(r'^password_reset/$', auth_views.password_reset, {'template_name': 'sesiones/password_reset_form.html',
                                                          'html_email_template_name': 'sesiones/password_reset_email.html',
                                                          'subject_template_name': 'sesiones/password_reset_subject.txt'
                                                          }, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, {'template_name': 'sesiones/password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, {'template_name': 'sesiones/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, {'template_name': 'sesiones/password_reset_complete.html'}, name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps_cenco/modulo_empleados/urls.py
from django.conf.urls import url
from apps_cenco.modulo_empleados import views

urlpatterns = [
    url(r'^consultar/$', views.consultar_empleados, name="consultar_empleados"),
    url(r'^verEmpleado/(?P<id_empleado>\d+)$', views.dir_ver_empleado, name='director_ver_empleado'),
    url(r'^crear/$', views.dir_crear_empleado, name="crear_empleado"),
    url(r'^consultar/inactivos/$', views.consultar_empleados_inactivos, name="consultar_empleados_inactivos"),
    url(r'^modificar/(?P<id_empleado>\d+)$', views.modificar_empleado, name="modificar_empleado"),
    url(r'^director_datos/$', views.director_datos_propios, name="director_datos_propios"),
    url(r'^director_datos_usuario/$', views.director_datos_propios_usuario, name="director_datos_propios_usuario"),
    url(r'^director_datos_correo/$', views.director_datos_propios_correo, name="director_datos_propios_correo"),
    url(r'^director_datos_contrasenia/$', views.director_datos_propios_contrasenia, name="director_datos_propios_contrasenia"),
    url(r'^misdatos/$', views.empleado_datos_propios, name="empleado_datos_propios"),
]

apps_cenco/db_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from time import strftime
from django.contrib.auth.models import User
from django.db import models


class Empleado (models.Model):
    codigo = models.AutoField(primary_key=True)
    username = models.OneToOneField(User, blank=True, null=True, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=40)
    apellido = models.CharField(max_length=40)
    direccion = models.TextField()
    correo = models.EmailField(blank=True)
    dui = models.CharField(max_length=10)
    isss = models.CharField(max_length=9)
    afp = models.CharField(max_length=12)
    nit = models.CharField(max_length=17)
    opciones_tipo = (
        ('Asi', 'Asistente'),
        ('Pro', 'Profesor'),
        ('Tec', 'Tecnico')
    )
    tipo = models.CharField(max_length=3, choices=opciones_tipo, default='Pro')

    opciones_estado=(
        ('activo','activo'),
        ('inactivo', 'inactivo')
    )

    estado=models.CharField(max_length=8, choices=opciones_estado, default='activo')

    def __unicode__(self):
        return self.nombre + " " + self.apellido


class Horario (models.Model):
    dias = (
        ('Lunes y Miercoles', 'Lunes y Miercoles'),
        ('Martes y Jueves', 'Martes y Jueves'),
        ('Domingo', 'Domingo'),
        ('Sabado', 'Sabado'),
        ('Viernes', 'Viernes')
    )
    codigo = models.AutoField(primary_key=True)
    dias_asignados = models.CharField(max_length=40, choices=dias)
    hora_inicio = models.TimeField(auto_now=False, auto_now_add=False)
    hora_fin = models.TimeField(auto_now=False, auto_now_add=False)
    cantidad_alumnos = models.IntegerField(default=0, blank=True)

    def __unicode__(self):
        acronimo = ""
        for i in self.dias_asignados.split(" "):
            acronimo += i[0]+" "
        # La I es para especificar un formato de 12 horas, la base tiene los registros en 24 horas.
        acronimo += " de " + self.hora_inicio.strftime("%I:%M") + " a " + self.hora_fin.strftime("%I:%M")
        return acronimo


class Grupo(models.Model):
    codigo = models.AutoField(primary_key=True)
    fechaInicio = models.DateField()
    alumnosInscritos = models.IntegerField(default=0)
    activo_grupo = models.BooleanField(default=True)
    # foreign keys
    horario = models.ForeignKey(Horario, on_delete=models.PROTECT)
    profesor = models.ForeignKey(Empleado, on_delete=models.PROTECT, blank=False)

    def __unicode__(self):
        return self.horario.__unicode__() + " (" + str(self.codigo) + ")"


class Encargado (models.Model):
    codigo = models.AutoField(primary_key=True)
    username = models.OneToOneField(User, blank=True, null=True, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=40)
    apellido = models.CharField(max_length=40)
    direccion = models.TextField()
    correo = models.EmailField(blank=True, null=True)
    dui = models.CharField(max_length=10, blank=True, null=True)

    def __unicode__(self):
        return self.nombre + " " + self.apellido


class Alumno (models.Model):
    codigo = models.AutoField(primary_key=True)
    username = models.OneToOneField(User, blank=True, null=True, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=40)
    apellido = models.CharField(max_length=40)
    direccion = models.TextField()
    correo = models.EmailField(blank=True, null=True)
    fechaNacimiento = models.DateField()
    dui = models.CharField(max_length=10, blank=True, null=True)
    solvente = models.BooleanField(default=False)
    # foreign keys
    encargado = models.ForeignKey(Encargado, on_delete=models.PROTECT, null=True, blank=True)
    # opciones_estado = (
    #     ('activo', 'activo'),
    #     ('inactivo', 'inactivo')
    # )
    #
    # estado = models.CharField(max_length=8, choices=opciones_estado, default='activo')
    def __unicode__(self):
        return self.nombre + " " + self.apellido

    class Meta:
        permissions = (
            ("ver_alumno", "Ver alumno"),
        )


class Telefono (models.Model):
    TIPOS_CHOICES = (('casa', 'Casa',), ('trabajo', 'Trabajo',), ('movil', 'Movil',))
    codigo = models.AutoField(primary_key=True)
    numero = models.CharField(max_length=8, null=False, blank=False)
    alumno = models.ForeignKey(Alumno, on_delete=models.CASCADE, null=True, blank=True)
    encargado = models.ForeignKey(Encargado, on_delete=models.CASCADE, null=True, blank=True)
    empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE, null=True, blank=True)
    tipo = models.CharField(max_length=20, choices=TIPOS_CHOICES)

    def __unicode__(self):
        return self.numero


# Modelos Agregados en Sprint 2

class Inscripcion(models.Model):
    codigo_ins = models.AutoField(primary_key=True)
    fecha_inscripcion = models.DateField()
    actual_inscripcion = models.BooleanField(default=True)
    # foreign keys
    alumno = models.ForeignKey(Alumno, on_delete=models.PROTECT, null=False, blank=False)
    grupo = models.ForeignKey(Grupo, on_delete=models.PROTECT, null=True, blank=True)


class Asistencia(models.Model):
    codigo_asistencia = models.AutoField(primary_key=True)
    fecha_asistencia = models.DateField()
    asistio = models.BooleanField(default=False)
    # foreign keys
    inscripcion = models.ForeignKey(Inscripcion, on_delete=models.CASCADE, null=False, blank=False)


class Estado(models.Model):
    codigo_estado = models.AutoField(primary_key=True)
    tipo_estado = models.CharField(max_length=20, null=False, blank=False)

    def __unicode__(self):
        return self.tipo_estado


class DetalleEstado(models.Model):
    codigo_detalle_e = models.AutoField(primary_key=True)
    fecha_detalle_e = models.DateField()
    actual_detalle_e = models.BooleanField(default=True)
    # foreign keys
    alumno = models.ForeignKey(Alumno, on_delete=models.CASCADE, null=False, blank=False)
    estado = models.ForeignKey(Estado, on_delete=models.CASCADE, null=False, blank=False)

    def __unicode__(self):
        return self.alumno.__unicode__() + " "+ self.estado.__unicode__() + " " + str(self.actual_detalle_e)


class Carrera(models.Model):
    codigo_carrera = models.AutoField(primary_key=True)
    nombre_carrera = models.CharField(max_length=20, null=False, blank=False)
    descripcion_carrera = models.CharField(max_length=200, null=False, blank=False)
    cuota_semanal_carrera = models.DecimalField(max_digits=10, decimal_places=2)
    precio_inscripcion_carrera = models.DecimalField(max_digits=10, decimal_places=2)
    activo_carrera = models.BooleanField(default=True)
    permitir_inscripcion = models.BooleanField(default=True)
    pensum_mes_carrera = models.IntegerField(blank=False, default=10)
    pensum_anio_carrera = models.IntegerField(blank=False, default=2018)


class Materia(models.Model):
    codigo_materia = models.AutoField(primary_key=True)
    nombre_materia = models.CharField(max_length=20, null=False, blank=False)
    descripcion_materia = models.CharField(max_length=200, null=False, blank=False)
    activo_materia = models.BooleanField(default=True)

    def __unicode__(self):
        return self.nombre_materia


class DetallePensum(models.Model):
    codigo_detalle_p = models.AutoField(primary_key=True)
    ordinal_materia_cursa = models.IntegerField(blank=False)
    # foreign keys
    materia = models.ForeignKey(Materia, on_delete=models.PROTECT, null=False, blank=False)
    carrera = models.ForeignKey(Carrera, on_delete=models.PROTECT, null=False, blank=False)


class Documento(models.Model):
    codigo_doc = models.AutoField(primary_key=True)
    nombre_doc = models.CharField(max_length=20, null=False, blank=False)
    descripcion_doc = models.CharField(max_length=200, null=False, blank=False)
    archivo = models.FileField(upload_to='documentos/')
    # foreign keys
    materia = models.ForeignKey(Materia, on_delete=models.PROTECT, null=False, blank=False)


class Expediente(models.Model):
    codigo_expediente = models.AutoField(primary_key=True)
    activo_expediente = models.BooleanField(default=True)
    fecha_inicio_exp = models.DateField()
    fecha_proximo_pago_exp = models.DateField()
    pagado_hasta = models.DateField()
    progreso_expediente = models.DecimalField(max_digits=4, decimal_places=2, default=0.0)
    # foreign keys
    alumno = models.ForeignKey(Alumno, on_delete=models.PROTECT, null=True)
    carrera = models.ForeignKey(Carrera, on_delete=models.PROTECT, null=True)


class Cursa(models.Model):
    codigo_cursa = models.AutoField(primary_key=True)
    nota_final = models.DecimalField(max_digits=6, decimal_places=4, null=True)
    actual_cursa = models.BooleanField(default=True)
    # foreign keys
    materia = models.ForeignKey(Materia, on_delete=models.PROTECT, null=False, blank=False)
    alumno = models.ForeignKey(Alumno, on_delete=models.PROTECT, null=False, blank=False)


class Examen(models.Model):
    codigo_examen = models.AutoField(primary_key=True)
    nombre_examen = models.CharField(max_length=100, null=False, blank=False)
    ponderacion_examen = models.DecimalField(max_digits=5, decimal_places=4)
    fecha_realizacion_examen= models.DateField()
    # foreign keys
    materia = models.ForeignKey(Materia, on_delete=models.PROTECT, null=False, blank=False)


class Evaluacion(models.Model):
    codigo_evaluacion = models.AutoField(primary_key=True)
    # nombre_evaluacion = models.CharField(max_length=100, null=False, blank=False)
    # ponderacion_evaluacion = models.DecimalField(max_digits=5, decimal_places=4)
    nota_evaluacion = models.DecimalField(max_digits=6, decimal_places=4, null=True)
    fecha_ingreso_evaluacion = models.DateField(auto_now=True)
    # fecha_realizacion_evaluacion = models.DateField()
    # foreign keys
    profesor = models.ForeignKey(Empleado, on_delete=models.PROTECT, null=True, blank=True)
    cursa = models.ForeignKey(Cursa, on_delete=models.PROTECT, null=False, blank=False)

apps_cenco/modulo_empleados/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps_cenco/modulo_empleados/forms.py
# -*- coding: utf-8 -*-
from django import forms

from apps_cenco.db_app.models import Empleado, Telefono


class CrearEmpleadoForm(forms.ModelForm):
    class Meta:
        model = Empleado
        fields = [
            'nombre',
            'apellido',
            'direccion',
            'correo',
            'dui',
            'isss',
            'afp',
            'nit',
            'tipo',
        ]
        labels = {
            'nombre': 'Nombre',
            'apellido': 'Apellido',
            'direccion': 'Dirección',
            'correo': 'Correo',
            'dui': 'DUI',
            'isss': 'ISSS',
            'afp': 'AFP',
            'nit': 'NIT',
            'tipo': 'Cargo que ocupa',
        }
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'required': True,
                                             'pattern': '^[ñÑa-zA-Z]+ ?[ñÑa-zA-Z]+$' ,'title': 'Ingrese su nombre o sus nombres con un espacio entre palabras'}),
            'apellido': forms.TextInput(attrs={'class': 'form-control', 'required': True,
                                               'pattern': '^[ñÑa-zA-Z]+ ?[ñÑa-zA-Z]+$', 'title': 'Ingrese su apellido o apellidos con un espacio entre palabras'}),
            'direccion': forms.TextInput(attrs={'class': 'form-control', 'required': True,
                                                'pattern': '^[ñÑa-zA-Z0-9, ]+$', 'title': 'Ingrese su dirección completa'}),
            'correo': forms.TextInput(attrs={'class': 'form-control', 'required': False,
                                             'pattern': '^[\w\d_\.]+@[\w\d_]+\.[\w\d_\.]+$',
                                             'title': 'Ejemplo: MiCorreo@gmail.com'}),
            'dui': forms.TextInput(attrs={'size': '27', 'class': 'form-control',
                                          'pattern': '^[0-9]{8}-[0-9]$', 'title': 'Ejemplo: 12345678-9'}),
            'isss': forms.TextInput(attrs={'class': 'form-control', 'required': True,
                                           'pattern': '^[0-9]{9}$', 'title': 'Ejemplo: 123456789'}),
            'afp': forms.TextInput(attrs={'class': 'form-control', 'required': True,
                                          'pattern': '^[0-9]{12}$', 'title': 'Ejemplo: 123456789012'}),
            'nit': forms.TextInput(attrs={'class': 'form-control', 'required': True,
                                          'pattern': '^[0-9]{4}-[0-9]{6}-[0-9]{3}-[0-9]$',
                                          'title': 'Ejemplo: 1012-010197-412-3'}),
            'tipo': forms.Select(attrs={'class': 'form-control', 'required': True}),
        }
 # formato nit ^[0-9]{4}-[0-9]{6}-[0-9]{3}-[0-9]$



class CrearTelefonoForm(forms.ModelForm):
    class Meta:
        model = Telefono
        fields = [
            'tipo',
            'numero'
        ]
        labels = {
            'tipo': 'Tipo de Teléfono',
            'numero': 'Número',
        }
        widgets = {
            'tipo': forms.Select(attrs={'class': 'form-control', 'required': True, 'id': 'id_tipo_telefono'}),
            'numero': forms.TextInput(attrs={'class': 'form-control', 'required': True}),
        }

    def add_prefix(self, field_name):
        FIELD_NAME_MAPPING = {'tipo': 'tipo_telefono'}
        # look up field name; return original if not found
        field_name = FIELD_NAME_MAPPING.get(field_name, field_name)
        return super(CrearTelefonoForm, self).add_prefix(field_name)

templates/modulo_empleados/asist_datos_propios.html
{% extends 'plantillas_base/base_asistente.html' %}

{% block titulo %}Mis Datos{% endblock %}

{% block head_content %}
{% endblock %}

{% block content %}
<div style="margin-left: 40px;">
<br>
<br>
    <h3>Mis Datos</h3>
<br>
<table class="table table-sm" style="width: 40%; white-space: normal;">
<tr><td><strong>Nombre:</strong> </td><td>{{ user.nombre }}</td></tr>
<tr><td><strong>Apellido:</strong> </td><td>{{ user.apellido }}</td></tr>
<tr><td><strong>Direcci&oacute;n:</strong> </td><td>{{ user.direccion }}</td></tr>
<tr><td><strong>Correo:</strong> </td><td>{{ user.correo }}</td></tr>
<tr><td><strong>DUI:</strong> </td><td>{{ user.dui }}</td></tr>
<tr><td><strong>ISSS:</strong> </td><td>{{ user.isss }}</td></tr>
<tr><td><strong>AFP:</strong> </td><td>{{ user.afp }}</td></tr>
<tr><td><strong>NIT:</strong> </td><td>{{ user.nit }}</td></tr>
<tr><td><strong>Cargo que ocupa:</strong> </td><td>{% if user.tipo == 'Asi' %}Asistente{% elif user.tipo == 'Pro' %}Profesor{% elif user.tipo == 'Tec' %}T&eacute;cnico{% endif %}</td></tr>
<tr><td><strong>Estado:</strong> </td><td>{{ user.estado }}</td></tr>
</table>
<br>
<table class="table table-sm" style="width: 40%;">
<th>Tel&eacute;fonos</th>
{% for tel in telefonos %}
    <tr><td>{{ tel.numero }}</td></tr>
{% endfor %}
</table>
</div>
<br>
{% endblock %}

templates/modulo_empleados/dir_crear_empleado.html
{% extends 'plantillas_base/base_director.html' %}
{% load staticfiles %}

{% block titulo %}Registro Empleado{% endblock %}

{% block head_content %}
    <link href=" {% static 'css/alerts_notificaciones.css' %} " rel="stylesheet">
    <script>
    $(document).on('submit', '#GuardarForm', function (a) {
        a.preventDefault();
        $('#btnGuardar').attr('disabled', true);
        $('#espereE').css('display', 'inline');
            $.ajax({
                type: 'POST',
                url: '/empleados/crear/',
                data: {
                    nombre: $('#id_nombre').val(),
                    apellido: $('#id_apellido').val(),
                    direccion: $('#id_direccion').val(),
                    correo: $('#id_correo').val(),
                    dui: $('#id_dui').val(),
                    isss: $('#id_isss').val(),
                    afp: $('#id_afp').val(),
                    nit: $('#id_nit').val(),
                    tipo: $('#id_tipo').val(),
                    tipo_telefono: $('#id_tipo_telefono').val(),
                    numero: $('#id_numero').val(),
                    csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]').val(),
                },
                success: function (response) {
                  $('#btnGuardar').attr('disabled', false);
                  $('#espereE').css('display', 'none');
                  var m = $('#mensajeEmergente');
                  m.children('strong').html(response);
                  m.css('display','block');
                  m.css('opacity',1);
                  m.removeClass();
                  m.addClass('alerta exito');
                  $("html, body").animate({ scrollTop: 0 }, "slow");
                },
                error: function (response) {
                  $('#btnGuardar').attr('disabled', false);
                  $('#espereE').css('display', 'none');
                  var m = $('#mensajeEmergente');
                  m.children('strong').html(response.responseText);
                  m.css('display','block');
                  m.css('opacity',1);
                  m.removeClass();
                  m.addClass('alerta accionPeligrosa');
                  $("html, body").animate({ scrollTop: 0 }, "slow");
                }
            })
        });


    </script>

{% endblock %}

{% block content %}

        <!-- ALERTAS -->
        <div class="divEscondido" id="mensajeEmergente">
        <span class="btnCerrar">&times;</span>
            <strong></strong>
        </div>
    <h3>Registrar Empleado</h3><br>
   <table width="50%" cellpadding="10px" cellspacing="10px">
    <tr>
        <td rowspan="16" width="70px"></td>
    </tr>
    <form method="POST" id="GuardarForm">
    {% csrf_token %}
        <tr><td colspan="2"><h4>Datos personales</h4></td></tr>
        <tr><th width="100px"></th>
            <td></td></tr>
    {{ form }}
       <tr><td colspan="2"><br><br> <h4>Tel&eacute;fono de contacto</h4></td></tr>
    {{ formT }}
    <tr>
        <td colspan="4">
            <button id="btnGuardar" type="submit" class="btn-primary" style="font-size: 20px">Registrar Nuevo Empleado</button>
            <div style="display: none" id="espereE">
                    <img src="{% static 'img/ajax-loader.gif' %}">
                    Procesando. Por Favor Espere.
            </div>
        </td>
    </tr>
    </form>
   </table>

    <script src="{% static 'js/cerrar_alertas.js' %}"></script>
{% endblock %}

templates/modulo_empleados/director_listaEmpleadosActivos.html
{% extends 'plantillas_base/base_director.html' %}
{% load staticfiles %}
{% block titulo %}Empleados Activos{% endblock %}

{% block head_content %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery/css/jquery.dataTables.min.css' %} ">
    <link href=" {% static 'css/formato_consultar_alumnos.css' %} " rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery/css/jquery.dataTables.min.css' %} ">
    <script src="{%  static 'js/consultar_alumnos.js' %}"></script>


    <style>
    a {
        color: black;
        text-underline-mode: none;
    }

    #example td, #example th{
        padding: 5px 5px 5px 5px;
        margin: 5px 5px 5px 5px;
        white-space: nowrap;
    }

    input{
        border-radius: 5px;
        border:1px solid #949494 !important;;
        padding: 3px;
        padding-left: 10px;

    }

    input:focus{
        border-radius: 5px;
        border:2px solid #2C3E50 !important;;
    }

    select {
       {#-webkit-appearance: button;#}
       -webkit-border-radius: 2px;
       -webkit-box-shadow: 0px 1px 1px rgba(0, 0, 0, 0.1);
       -webkit-padding-end: 10px;
       -webkit-padding-start: 2px;
       -webkit-user-select: none;
       background-position: 97% center;
       background-repeat: no-repeat;
       border: 1px solid #828282;
       color: #000000;
       overflow: hidden;
       padding: 2px 10px;
       text-overflow: ellipsis;
       white-space: nowrap;
        height: 30px;
        margin-right: 5px;
        margin-left: 5px;

    }



    </style>

{% endblock %}

{% block content %}
<table align="center">

    <tr align="left">


    </tr>

    <tr>
    <td width="10px"></td>
    <td width="900px">
        <div style="padding-top: 30px;">
            <h4>Empleados Activos</h4>
        </div>

        <div style="text-align: right; align-items: right; padding-bottom: 20px;">
            <a href="{% url 'crear_empleado' %}"><button style="margin-right: 10px" type="button" class="btn btn-primary">Nuevo empleado</button></a>

            <a href="{% url 'consultar_empleados_inactivos' %}"><button type="button" class="btn btn-primary">Ver Inactivos</button></a>

        </div>
        <table id="example" class="table table-bordered table-hover table-sm" style="width:100%;">
            <thead>
                <tr bgcolor="#f0f8ff" >

                    <th>Nombres</th>
                    <th>Apellidos</th>
                    <th>Telefono</th>
                    <th>Tipo</th>
                    <th>Correo</th>

                </tr>
            </thead>
                </thead>
                <tbody>
                {% for user in empleados%}
                    <tr>
                        <td><a href="{% url 'director_ver_empleado' id_empleado=user.codigo %}">{{ user.nombre }}</a></td>
                        <td>{{ user.apellido }} </td>
                        <td>{{ user.primerTelefono|default_if_none:"" }}</td>
                        <td>{{ user.primerTelefono.tipo|default_if_none:""  }}</td>
                        <td>{{ user.correo|default_if_none:"" }}</td>

                    </tr>
                {% endfor %}
                </tbody>
        </table>
    </td>
    <td width="10px"></td>
    </tr>



</table>



    <script type="text/javascript" charset="utf8" src="{% static 'js/jquery/jquery.dataTables.min.js' %} "></script>
    <script>
        $(document).ready(function() {
        var tabla = $('#example').DataTable( {
         "language": {
            "lengthMenu": "Mostrando _MENU_ registros por p&aacute;gina",
            "zeroRecords": "No se encontr&oacute; nada",
            "info": "Mostrando p&aacute;ginas _PAGE_ de _PAGES_",
            "infoEmpty": "vac&iacute;o",
            "infoFiltered": "(filtrados de _MAX_ registros totales)",
            "decimal":        "",
            "emptyTable":     "No hay datos disponibles",
            "infoPostFix":    "",
            "thousands":      ",",
            "loadingRecords": "Cargando registros...",
            "processing":     "Procesando...",
            "search":         "Buscar:",
            "paginate": {
                "first":      "Ir al primero",
                "last":       "Ir al &uacute;ltimo",
                "next":       "Siguiente",
                "previous":   "Anterior"
            },
            "aria": {
                "sortAscending":  ": ordenar columnas en orden ascendente",
                "sortDescending": ": ordenar columnas en orden descendente"
            }
        }});

        tabla.$('tr').click(function() {
            var href = $(this).find("a").attr("href");
            if(href) {
                window.location = href;
            }
        });

    });
    </script>

{% endblock %}