academica_cenco/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import include

from apps_cenco.login.views import *
from apps_cenco.modulo_grupos.views import *
from apps_cenco.modulo_alumnos.views import *
from django.contrib.auth import views as auth_views

#  {'next_page': '/login'}

urlpatterns = [
    url(r'^$', principal, name="inicio"),  # Valida que sucede cuando se entra al localhost:8000/
    url(r'^accounts/login/$', auth_views.login, {'template_name': 'sesiones/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'sesiones/logout.html'}, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^grupos/', include('apps_cenco.modulo_grupos.urls')),
    url(r'^credenciales/', include('apps_cenco.login.urls')),
    url(r'^alumnos/', include('apps_cenco.modulo_alumnos.urls')),
    url(r'^horarios/', include('apps_cenco.modulo_horarios.urls')),
    url(r'^configuracion/', include('apps_cenco.db_local.urls')),
    url(r'^asistencia/', include('apps_cenco.modulo_asistencia.urls')),
    url(r'^empleados/', include('apps_cenco.modulo_empleados.urls')),
    url(r'^carrera/', include('apps_cenco.modulo_carrera.urls')),
    url(r'^materia/', include('apps_cenco.modulo_materia.urls')),
    url(r'^notas/',  include('apps_cenco.modulo_notas.urls')),
    url(r'^pagos/',  include('apps_cenco.modulo_pagos.urls')),
    url(r'^practicas/',  include('apps_cenco.modulo_practicas.urls')),

    # for reset passwords
    url(r'^password_reset/$', auth_views.password_reset, {'template_name': 'sesiones/password_reset_form.html',
                                                          'html_email_template_name': 'sesiones/password_reset_email.html',
                                                          'subject_template_name': 'sesiones/password_reset_subject.txt'
                                                          }, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, {'template_name': 'sesiones/password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, {'template_name': 'sesiones/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, {'template_name': 'sesiones/password_reset_complete.html'}, name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps_cenco/modulo_carrera/urls.py
from django.conf.urls import url
from apps_cenco.modulo_carrera import views as carrViews

urlpatterns = [
    url(r'^crear_carrera/$', carrViews.crear_carrera),
    url(r'^editar_carrera/(?P<id_carrera>\d+)$', carrViews.editar_carrera),
    url(r'^crear_pensum/(?P<id_carrera>\d+)$', carrViews.crear_pensum),
    url(r'^consultar_carreras/$', carrViews.consultar_carrera),
]

apps_cenco/db_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from time import strftime
from django.contrib.auth.models import User
from django.db import models


class Empleado (models.Model):
    codigo = models.AutoField(primary_key=True)
    username = models.OneToOneField(User, blank=True, null=True, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=40)
    apellido = models.CharField(max_length=40)
    direccion = models.TextField()
    correo = models.EmailField(blank=True)
    dui = models.CharField(max_length=10)
    isss = models.CharField(max_length=9)
    afp = models.CharField(max_length=12)
    nit = models.CharField(max_length=17)
    opciones_tipo = (
        ('Asi', 'Asistente'),
        ('Pro', 'Profesor'),
        ('Tec', 'Tecnico')
    )
    tipo = models.CharField(max_length=3, choices=opciones_tipo, default='Pro')

    opciones_estado=(
        ('activo','activo'),
        ('inactivo', 'inactivo')
    )

    estado=models.CharField(max_length=8, choices=opciones_estado, default='activo')

    def __unicode__(self):
        return self.nombre + " " + self.apellido


class Horario (models.Model):
    dias = (
        ('Lunes y Miercoles', 'Lunes y Miercoles'),
        ('Martes y Jueves', 'Martes y Jueves'),
        ('Domingo', 'Domingo'),
        ('Sabado', 'Sabado'),
        ('Viernes', 'Viernes')
    )
    codigo = models.AutoField(primary_key=True)
    dias_asignados = models.CharField(max_length=40, choices=dias)
    hora_inicio = models.TimeField(auto_now=False, auto_now_add=False)
    hora_fin = models.TimeField(auto_now=False, auto_now_add=False)
    cantidad_alumnos = models.IntegerField(default=0, blank=True)

    def __unicode__(self):
        acronimo = ""
        for i in self.dias_asignados.split(" "):
            acronimo += i[0]+" "
        # La I es para especificar un formato de 12 horas, la base tiene los registros en 24 horas.
        acronimo += " de " + self.hora_inicio.strftime("%I:%M") + " a " + self.hora_fin.strftime("%I:%M")
        return acronimo


class Grupo(models.Model):
    codigo = models.AutoField(primary_key=True)
    fechaInicio = models.DateField()
    alumnosInscritos = models.IntegerField(default=0)
    activo_grupo = models.BooleanField(default=True)
    # foreign keys
    horario = models.ForeignKey(Horario, on_delete=models.PROTECT)
    profesor = models.ForeignKey(Empleado, on_delete=models.PROTECT, blank=False)

    def __unicode__(self):
        return self.horario.__unicode__() + " (" + str(self.codigo) + ")"


class Encargado (models.Model):
    codigo = models.AutoField(primary_key=True)
    username = models.OneToOneField(User, blank=True, null=True, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=40)
    apellido = models.CharField(max_length=40)
    direccion = models.TextField()
    correo = models.EmailField(blank=True, null=True)
    dui = models.CharField(max_length=10, blank=True, null=True)

    def __unicode__(self):
        return self.nombre + " " + self.apellido


class Alumno (models.Model):
    codigo = models.AutoField(primary_key=True)
    username = models.OneToOneField(User, blank=True, null=True, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=40)
    apellido = models.CharField(max_length=40)
    direccion = models.TextField()
    correo = models.EmailField(blank=True, null=True)
    fechaNacimiento = models.DateField()
    dui = models.CharField(max_length=10, blank=True, null=True)
    solvente = models.BooleanField(default=False)
    # foreign keys
    encargado = models.ForeignKey(Encargado, on_delete=models.PROTECT, null=True, blank=True)
    # opciones_estado = (
    #     ('activo', 'activo'),
    #     ('inactivo', 'inactivo')
    # )
    #
    # estado = models.CharField(max_length=8, choices=opciones_estado, default='activo')
    def __unicode__(self):
        return self.nombre + " " + self.apellido

    class Meta:
        permissions = (
            ("ver_alumno", "Ver alumno"),
        )


class Telefono (models.Model):
    TIPOS_CHOICES = (('casa', 'Casa',), ('trabajo', 'Trabajo',), ('movil', 'Movil',))
    codigo = models.AutoField(primary_key=True)
    numero = models.CharField(max_length=8, null=False, blank=False)
    alumno = models.ForeignKey(Alumno, on_delete=models.CASCADE, null=True, blank=True)
    encargado = models.ForeignKey(Encargado, on_delete=models.CASCADE, null=True, blank=True)
    empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE, null=True, blank=True)
    tipo = models.CharField(max_length=20, choices=TIPOS_CHOICES)

    def __unicode__(self):
        return self.numero


# Modelos Agregados en Sprint 2

class Inscripcion(models.Model):
    codigo_ins = models.AutoField(primary_key=True)
    fecha_inscripcion = models.DateField()
    actual_inscripcion = models.BooleanField(default=True)
    # foreign keys
    alumno = models.ForeignKey(Alumno, on_delete=models.PROTECT, null=False, blank=False)
    grupo = models.ForeignKey(Grupo, on_delete=models.PROTECT, null=True, blank=True)


class Asistencia(models.Model):
    codigo_asistencia = models.AutoField(primary_key=True)
    fecha_asistencia = models.DateField()
    asistio = models.BooleanField(default=False)
    # foreign keys
    inscripcion = models.ForeignKey(Inscripcion, on_delete=models.CASCADE, null=False, blank=False)


class Estado(models.Model):
    codigo_estado = models.AutoField(primary_key=True)
    tipo_estado = models.CharField(max_length=20, null=False, blank=False)

    def __unicode__(self):
        return self.tipo_estado


class DetalleEstado(models.Model):
    codigo_detalle_e = models.AutoField(primary_key=True)
    fecha_detalle_e = models.DateField()
    actual_detalle_e = models.BooleanField(default=True)
    # foreign keys
    alumno = models.ForeignKey(Alumno, on_delete=models.CASCADE, null=False, blank=False)
    estado = models.ForeignKey(Estado, on_delete=models.CASCADE, null=False, blank=False)

    def __unicode__(self):
        return self.alumno.__unicode__() + " "+ self.estado.__unicode__() + " " + str(self.actual_detalle_e)


class Carrera(models.Model):
    codigo_carrera = models.AutoField(primary_key=True)
    nombre_carrera = models.CharField(max_length=20, null=False, blank=False)
    descripcion_carrera = models.CharField(max_length=200, null=False, blank=False)
    cuota_semanal_carrera = models.DecimalField(max_digits=10, decimal_places=2)
    precio_inscripcion_carrera = models.DecimalField(max_digits=10, decimal_places=2)
    activo_carrera = models.BooleanField(default=True)
    permitir_inscripcion = models.BooleanField(default=True)
    pensum_mes_carrera = models.IntegerField(blank=False, default=10)
    pensum_anio_carrera = models.IntegerField(blank=False, default=2018)


class Materia(models.Model):
    codigo_materia = models.AutoField(primary_key=True)
    nombre_materia = models.CharField(max_length=20, null=False, blank=False)
    descripcion_materia = models.CharField(max_length=200, null=False, blank=False)
    activo_materia = models.BooleanField(default=True)

    def __unicode__(self):
        return self.nombre_materia


class DetallePensum(models.Model):
    codigo_detalle_p = models.AutoField(primary_key=True)
    ordinal_materia_cursa = models.IntegerField(blank=False)
    # foreign keys
    materia = models.ForeignKey(Materia, on_delete=models.PROTECT, null=False, blank=False)
    carrera = models.ForeignKey(Carrera, on_delete=models.PROTECT, null=False, blank=False)


class Documento(models.Model):
    codigo_doc = models.AutoField(primary_key=True)
    nombre_doc = models.CharField(max_length=20, null=False, blank=False)
    descripcion_doc = models.CharField(max_length=200, null=False, blank=False)
    archivo = models.FileField(upload_to='documentos/')
    # foreign keys
    materia = models.ForeignKey(Materia, on_delete=models.PROTECT, null=False, blank=False)


class Expediente(models.Model):
    codigo_expediente = models.AutoField(primary_key=True)
    activo_expediente = models.BooleanField(default=True)
    fecha_inicio_exp = models.DateField()
    fecha_proximo_pago_exp = models.DateField()
    pagado_hasta = models.DateField()
    progreso_expediente = models.DecimalField(max_digits=4, decimal_places=2, default=0.0)
    # foreign keys
    alumno = models.ForeignKey(Alumno, on_delete=models.PROTECT, null=True)
    carrera = models.ForeignKey(Carrera, on_delete=models.PROTECT, null=True)


class Cursa(models.Model):
    codigo_cursa = models.AutoField(primary_key=True)
    nota_final = models.DecimalField(max_digits=6, decimal_places=4, null=True)
    actual_cursa = models.BooleanField(default=True)
    # foreign keys
    materia = models.ForeignKey(Materia, on_delete=models.PROTECT, null=False, blank=False)
    alumno = models.ForeignKey(Alumno, on_delete=models.PROTECT, null=False, blank=False)


class Examen(models.Model):
    codigo_examen = models.AutoField(primary_key=True)
    nombre_examen = models.CharField(max_length=100, null=False, blank=False)
    ponderacion_examen = models.DecimalField(max_digits=5, decimal_places=4)
    fecha_realizacion_examen= models.DateField()
    # foreign keys
    materia = models.ForeignKey(Materia, on_delete=models.PROTECT, null=False, blank=False)


class Evaluacion(models.Model):
    codigo_evaluacion = models.AutoField(primary_key=True)
    # nombre_evaluacion = models.CharField(max_length=100, null=False, blank=False)
    # ponderacion_evaluacion = models.DecimalField(max_digits=5, decimal_places=4)
    nota_evaluacion = models.DecimalField(max_digits=6, decimal_places=4, null=True)
    fecha_ingreso_evaluacion = models.DateField(auto_now=True)
    # fecha_realizacion_evaluacion = models.DateField()
    # foreign keys
    profesor = models.ForeignKey(Empleado, on_delete=models.PROTECT, null=True, blank=True)
    cursa = models.ForeignKey(Cursa, on_delete=models.PROTECT, null=False, blank=False)

apps_cenco/modulo_carrera/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps_cenco/modulo_carrera/forms.py
# -*- coding: utf-8 -*-
from django import forms

from apps_cenco.db_app.models import Carrera


class CrearEditarCarreraForm(forms.ModelForm):
    class Meta:
        model = Carrera
        fields = [
            'nombre_carrera',
            'descripcion_carrera',
            'cuota_semanal_carrera',
            'precio_inscripcion_carrera',
        ]

        labels = {
            'nombre_carrera':   'Nombre de la Carrera',
            'descripcion_carrera':  'Descripción',
            'cuota_semanal_carrera': 'Cuota Semanal',
            'precio_inscripcion_carrera':   'Costo de Inscripción',
        }

        widgets = {
            'nombre_carrera': forms.TextInput(attrs={'class': 'form-control', 'required': True}),
            'descripcion_carrera': forms.TextInput(attrs={'class': 'form-control', 'required': True}),
            'cuota_semanal_carrera': forms.NumberInput(attrs={'class': 'form-control', 'required': True}),
            'precio_inscripcion_carrera': forms.NumberInput(attrs={'class': 'form-control', 'required': True}),
        }

apps_cenco/modulo_carrera/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import json
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from apps_cenco.db_app.models import Carrera, Materia, Cursa, DetallePensum
from apps_cenco.modulo_carrera.forms import CrearEditarCarreraForm


@login_required
def crear_carrera(request):
    editar = False
    if request.method == 'POST':
        print ('datos POST')
        print (request.POST)
        form = CrearEditarCarreraForm(request.POST)
        if form.is_valid():
            carrera = form.save(commit=False)
            carrera.pensum_mes_carrera = datetime.today().month
            carrera.pensum_anio_carrera = datetime.today().year
            carrera.save()
            return HttpResponse('Se ha guardado la nueva carrera correctamente')
        else:
            return HttpResponse('Se recibieron datos incorrectos', status=500)
    else:
        form = CrearEditarCarreraForm()
        context = {'form': form, 'editar': editar}
        return render(request,  'modulo_carrera/crear_editar_carrera.html', context)


@login_required
def editar_carrera(request, id_carrera):
    editar = True
    if request.method == 'POST':
        carrera = Carrera.objects.get(codigo_carrera=id_carrera)
        form = CrearEditarCarreraForm(request.POST, instance=carrera)
        if form.is_valid():
            form.save()
            return HttpResponse('Información de la carrera actualizada correctamente')
        else:
            return HttpResponse('Se recibieron datos incorrectos', status=500)
    else:
        carrera = Carrera.objects.get(codigo_carrera= id_carrera)
        form = CrearEditarCarreraForm(instance=carrera)
        context = {'form': form, 'editar': editar, 'id_carrera': id_carrera}
        return render(request, 'modulo_carrera/crear_editar_carrera.html', context)


@login_required
def crear_pensum(request, id_carrera):
    detalle_pensumE = DetallePensum.objects.filter(carrera_id=id_carrera).distinct('carrera_id')
    if not detalle_pensumE:
        carrera = Carrera.objects.get(codigo_carrera=id_carrera)
        if request.method == 'POST':
            lista = request.POST.get('lista')
            list_data = json.loads(lista)
            for a in list_data:
                materia = Materia.objects.get(codigo_materia=list_data[a])
                detalle_pensum = DetallePensum(carrera=carrera, materia=materia, ordinal_materia_cursa=int(a)+1)
                detalle_pensum.save()
            return HttpResponse('Pensum creado con exito.')
        else:
            materias = Materia.objects.all()
            context = {'carrera': carrera, 'materias': materias}
            return render(request, 'modulo_carrera/crear_pensum.html', context)
    else:
        context = {'existente': True}
        return render(request, 'modulo_carrera/crear_pensum.html', context)


@login_required
def consultar_carrera(request):
    carreras = Carrera.objects.all().order_by('codigo_carrera')
    pensum = DetallePensum.objects.all().order_by('ordinal_materia_cursa')
    context = {'carreras': carreras, 'pensum': pensum}
    return render(request, 'modulo_carrera/consultar_carreras.html', context)

templates/modulo_carrera/consultar_carreras.html
{% extends 'plantillas_base/base_director.html' %}
{% load staticfiles %}
{% block titulo %}Consultar Carreras{% endblock %}

{% block head_content %}
<link href=" {% static 'css/contenido_colapsable.css' %} " rel="stylesheet">
{% endblock %}

{% block content %}
    <br>
    <h3>Consultar Carreras Disponibles</h3>
    <br>
    {% for c in carreras %}
    <p></p>
        <button class="collapsible" style="width: 80%;"><strong><div style="display: inline-block;" class="accion">[Expandir &#9660;]</div> &nbsp; &nbsp;&nbsp; {{ c.nombre_carrera }}</strong></button>
        <div class="content" style="width: 80%">
    <table class="table border-dark">
        <thead>
        <th style="width: 100px">No. de Curso</th>
        <th style="width: 150px">Nombre Materia</th>
        <th>Descripci&oacute;n</th>
        </thead>
    <tbody>
    {% for p in pensum %}
        {% if c == p.carrera %}
           <tr><td>{{ p.ordinal_materia_cursa }}</td><td>{{ p.materia.nombre_materia }}</td><td>{{ p.materia.descripcion_materia }}</td></tr>
        {% endif %}
    {% endfor %}
    </tbody>
    </table>
    </div>
    {% endfor %}

<script src="{% static 'js/contenido_colapsable.js' %}"></script>
{% endblock %}

templates/modulo_carrera/crear_editar_carrera.html
{% extends 'plantillas_base/base_director.html' %}
{% load staticfiles %}
{% block titulo %}{% if editar %}Editar{% else %}Crear{% endif %} Carrera{% endblock %}

{% block head_content %}
    <link href=" {% static 'css/alerts_notificaciones.css' %} " rel="stylesheet">
    <script>
   $(document).on('submit', '#crearEditarform', function (a) {
       a.preventDefault();
       $('#btnGuardar').attr('disabled', true);
       $('#espereG').css('display', 'inline');
            $.ajax({
                type: 'POST',
                {% if editar %}
                url: '/carrera/editar_carrera/{{ id_carrera }}',
                {% else %}
                url: '/carrera/crear_carrera/',
                {% endif %}
                data: {
                    nombre_carrera: $('#id_nombre_carrera').val(),
                    descripcion_carrera: $('#id_descripcion_carrera').val(),
                    cuota_semanal_carrera: $('#id_cuota_semanal_carrera').val(),
                    precio_inscripcion_carrera: $('#id_precio_inscripcion_carrera').val(),
                    csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]').val(),
                },
                success: function (response) {
                  $('#btnGuardar').attr('disabled', false);
                  $('#espereG').css('display', 'none');
                  var m = $('#mensajeEmergente');
                  m.children('strong').html(response);
                  m.css('display','block');
                  m.css('opacity',1);
                  m.removeClass();
                  m.addClass('alerta exito');
                },
                error: function (response) {
                  $('#btnGuardar').attr('disabled', false);
                  $('#espereG').css('display', 'none');
                  var m = $('#mensajeEmergente');
                  m.children('strong').html(response.responseText);
                  m.css('display','block');
                  m.css('opacity',1);
                  m.removeClass();
                  m.addClass('alerta cuidado');
                  $("html, body").animate({ scrollTop: 0 }, "slow");
                }
            })
    })
    </script>


{% endblock %}

{% block content %}
    <br>
        <!-- ALERTAS -->
        <div class="divEscondido" id="mensajeEmergente">
        <span class="btnCerrar">&times;</span>
            <strong></strong>
        </div>
    <br>
    <h3>{% if editar %}Editar Una{% else %}Crear Nueva{% endif %} Carrera</h3>
    <form method="POST" action="" id="crearEditarform">
    {% csrf_token %}
        <table width="50%" cellpadding="10px">
    <tr><td width="100px"></td><td></td></tr>

    {{ form }}
    </table>
    <input type="submit" class="btn-primary btn" style="font-size: 20px" value="{% if editar %}Editar{% else %}Crear{% endif %} Carrera" id="btnGuardar" >
        <div style="display: none" id="espereG">
            <img src="{% static 'img/ajax-loader.gif' %}">
            Procesando. Por Favor Espere.
        </div>
    </form>

    <script src="{% static 'js/cerrar_alertas.js' %}"></script>
{% endblock %}

templates/modulo_carrera/crear_pensum.html
{% extends 'plantillas_base/base_director.html' %}
{% load staticfiles %}
{% block titulo %}Crear Nuevo Pensum{% endblock %}

{% block head_content %}
    <link rel="stylesheet" href="{% static 'css/jquery-1.12.1ui/jquery-ui.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <style>
  #elegible { list-style-type: none; margin: 0; padding: 0; margin-bottom: 10px; }
  .draggable { margin: 5px; padding: 5px; width: 150px; }
  </style>

  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

  <script>
  $( function() {
    $( "#sortable" ).sortable({
      revert: false
    });
    $( ".draggable" ).draggable({
      connectToSortable: "#sortable",
      {#helper: "clone",#}
      revert: "invalid"
    });
    $( " ul, li" ).disableSelection();

  } );

  $(function () {
      $('#elegible').mousedown(function () {
          $('#arrastrable').removeClass('overflow-y');
          $('#arrastrable').css('overflow', 'visible');
      });
      $("html, body").mouseup(function () {
          $('#arrastrable').css('overflow-y', 'scroll');
      });
  });

  </script>

    <link href=" {% static 'css/alerts_notificaciones.css' %} " rel="stylesheet">
    <script>
   $(document).on('submit', '#crearForm', function (a) {

        var list = {};
        var nodos = document.getElementById("sortable").getElementsByTagName("li");
        for (var i = 0; i < nodos.length; i++) {
            list[i]=nodos.item(i).id;
        }
        console.log(list);

       a.preventDefault();
       $('#btnGuardar').attr('disabled', true);
       $('#espereG').css('display', 'inline');
            $.ajax({
                type: 'POST',

                url: '/carrera/crear_pensum/{{ carrera.codigo_carrera }}',
                datatype: 'json',
                data: {
                    lista: JSON.stringify(list),
                    csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]').val(),
                },
                success: function (response) {
                  $('#btnGuardar').attr('disabled', false);
                  $('#espereG').css('display', 'none');
                  var m = $('#mensajeEmergente');
                  m.children('strong').html(response);
                  m.css('display','block');
                  m.css('opacity',1);
                  m.removeClass();
                  m.addClass('alerta exito');
                  $("html, body").animate({ scrollTop: 0 }, "slow");
                },
                error: function (response) {
                  $('#btnGuardar').attr('disabled', false);
                  $('#espereG').css('display', 'none');
                  var m = $('#mensajeEmergente');
                  m.children('strong').html(response.responseText);
                  m.css('display','block');
                  m.css('opacity',1);
                  m.removeClass();
                  m.addClass('alerta cuidado');
                  $("html, body").animate({ scrollTop: 0 }, "slow");
                }
            })
    })
    </script>


{% endblock %}

{% block content %}
    {% if not existente %}
        <!-- ALERTAS -->
        <div class="divEscondido" id="mensajeEmergente">
        <span class="btnCerrar">&times;</span>
            <strong></strong>
        </div>
    <h3>Crear Pensum para: {{ carrera.nombre_carrera }}</h3>
    <br>
    <h4><strong>Descripci&oacute;n: </strong></h4>
    <h4>{{ carrera.descripcion_carrera }}</h4>
    <br>
    <div id="arrastrable"; style="display: inline-block; border: 1px solid black; width: 400px; height: 400px;vertical-align: top; padding: 20px; overflow-y: scroll;  " >
    <h4>Materias Disponibles</h4>
    <ul id="elegible">
  {% for m in materias %}
  <li id="{{ m.codigo_materia }}" class="ui-state-focus draggable">{{ m.nombre_materia }}</li>
    {% endfor %}
</ul>
</div>
<div style="display: inline-block; border: 1px solid black; width: 400px; height: 400px; vertical-align: top; padding: 20px; overflow-y: scroll;" >
<h4>Orden en el Nuevo Pensum</h4>
<ol id="sortable" style="width: 350px; min-height: 1400px;">

</ol>
</div>
<br><br>
<form id="crearForm" method="POST">
{% csrf_token %}
<input type="submit" value="Guardar Pensum" class="btn-primary btn">
    <div style="display: none" id="espereG">
        <img src="{% static 'img/ajax-loader.gif' %}">
        Procesando. Por Favor Espere.
    </div>
    </form>
<script src="{% static 'js/cerrar_alertas.js' %}"></script>
{% else %}
    <script>
    $(function () {
        var m = $('#mensajeEmergente');
        m.css('display','block');
        m.css('opacity',1);
        m.removeClass();
        m.addClass('alerta cuidado');

       });
    </script>

            <!-- ALERTAS -->
        <div class="divEscondido" id="mensajeEmergente">
        <span class="btnCerrar"></span>
            <strong>La carrera seleccionada ya tiene un pensum asignado.</strong>
        </div>

{% endif %}

{% endblock %}